{
  "hash": "10bb1f99d79a398d3e52c71733407afb",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Part 3: Fitting Survival Distributions to Data\"\nauthor: \"Madhav Prashanth Ramachandran\"\ndate: \"2026-04-19\"\ncategories: [survival analysis, statistics, python, MLE]\n---\n\n\n## Recap of Part 2 and What's Coming in Part 3\n\nIn [**Part 2**](https://madhavpr191221.github.io/blog/posts/part2-distributions-in-survival-analysis/), we built a vocabulary of survival distributions — the Exponential \nfor constant hazard, the Rayleigh for linearly increasing hazard, and the Weibull \nas the unifying family that contains both as special cases. Along the way we took \na detour through the connection between the Rayleigh, Normal, and Exponential \ndistributions, and ended with the bathtub curve — the most common failure pattern \nin real engineered systems.\n\nBut a distribution is not a model until it is fit to data. In **Part 3**, we ask: \ngiven a dataset of failure times — some exact, some censored — how do we estimate \nthe parameters of these distributions? We will derive the likelihood function under \ncensoring from first principles, apply maximum likelihood estimation, and assess \nthe quality of our fits using diagnostic tools. Python code throughout using \n`lifelines`.\n\n\n### Maximum Likelihood Estimation \n\nWe will review the maximum likelihood estimation (MLE) framework with a simple example. We will then extend this framework to handle censored data, which is what makes survival analysis different from classical statistical inference. We will derive the likelihood function for censored data, and then apply MLE to estimate the parameters of the distributions we have discussed. We will simulate some synthetic data to demonstrate the MLE process in practice. If you are new to MLE and feel lost, you can consult any standard statistics textbook or an online resource for a more detailed introduction. The key idea is that MLE provides a systematic way to estimate the parameters of a statistical model by finding the parameter values that maximize the likelihood of observing the given data. \n\n\n#### The Likelihood Function \n\nThis is the heart of the matter. Likelihoods often are confused with probabilities -- they look similar, their forms are similar but they are conceptually different. In probability, we ask: given a model with known parameters, what is the chance of observing the data? In likelihood, we ask: given the observed data, what is the chance that the data came from a model with certain parameters? To give a concrete example, suppose we observe a failure time of 5 hours. Let's suppose we have a model that says the failure time follows an exponential distribution with a mean of 10 hours. Probability asks: What is the probability of observing a failure between 4 and 6 hours given this model? Likelihood asks: Across all possible values of the mean (or rate) parameter, for which value does the observed time of 5 hours seems most plausible? \n\nHere is the setup. We have a sequence of observed failure times $t_1, t_2, \\ldots, t_n$ that we assume are independent and identically distributed (i.i.d.) samples from some distribution with a parameter $\\theta$. The likelihood function is defined as the joint probability of observing this data given the parameter $\\theta$: In the simplest setup, we will assume that all observations are exact failure times (no censoring). In that case, the likelihood function is:\n\n$$L(\\theta) = P(t_1, t_2, \\ldots, t_n ; \\theta)$$\n\nNote that this is a function of $\\theta$ - we are treating the data as fixed and asking how likely different values of $\\theta$ are to have generated this data. Since most of our work will involve continuous distributions, we will often work with the probability density function (pdf) instead of the probability mass function (pmf). In that case, the likelihood becomes:\n\n$$L(\\theta) = f(t_1 ; \\theta) \\cdot f(t_2 ; \\theta) \\cdot \\ldots \\cdot f(t_n ; \\theta) = \\prod_{i=1}^n f(t_i ; \\theta)$$\n\nNote that some authors use the conditional probability notation $P(t_i | \\theta)$ instead of the joint probability notation $P(t_1, t_2, \\ldots, t_n ; \\theta)$, but the meaning is the same. The likelihood function captures how well the model with parameter $\\theta$ explains the observed data. The MLE process will involve finding the value of $\\theta$ that maximizes this likelihood function. We will use the semicolons in the notation to emphasize that we are treating the data as fixed and the parameter as an unknown constant. If the parameter is itself a random variable with a prior distribution, then we are in the realm of Bayesian inference, which is a different framework. In MLE, we do not assign a prior distribution to the parameter; we simply find the value that maximizes the likelihood of the observed data.\n\n\n#### The Maximum Likelihood Estimation Process\n\nThe MLE process involves finding the value of $\\theta$ that maximizes the likelihood function $L(\\theta)$. In practice, it is often easier to work with the log-likelihood function, which is the natural logarithm of the likelihood:\n\n$$\\ell(\\theta) = \\log L(\\theta) = \\sum_{i=1}^n \\log f(t_i ; \\theta)$$\n\nThe MLE estimate $\\hat{\\theta}_{\\text{MLE}}$ is the value of $\\theta$ that maximizes $\\ell(\\theta)$: \n\n$$\\hat{\\theta}_{\\text{MLE}} = \\arg\\max_{\\theta} \\ell(\\theta)$$\n\nIf the likelihood function is well-behaved (e.g., it is differentiable), we can find the MLE estimate by taking the derivative of the log-likelihood with respect to $\\theta$, setting it equal to zero, and solving for $\\theta$. This gives us the critical points of the log-likelihood function, which we can then evaluate to find the maximum. To show that the critical point we find is indeed a maximum, we can check the second derivative or use other methods if necessary. Let's see how this works in practice with a simple example. \n\nSuppose we have a dataset of failure times that we believe follows an exponential distribution. The exponential distribution has a single parameter $\\lambda$ (the rate), and its pdf is given by:\n\n$$f(t ; \\lambda) = \\lambda e^{-\\lambda t}$$\n\nGiven a dataset of failure times $t_1, t_2, \\ldots, t_n$, the likelihood function for the exponential distribution is:\n\n$$L(\\lambda) = \\prod_{i=1}^n \\lambda e^{-\\lambda t_i} = \\lambda^n e^{-\\lambda \\sum_{i=1}^n t_i}$$\n\nThe log-likelihood function is:\n\n$$\\ell(\\lambda) = n \\log \\lambda - \\lambda \\sum_{i=1}^n t_i$$\n\nTo find the MLE estimate $\\hat{\\lambda}$, we take the derivative of $\\ell(\\lambda)$ with respect to $\\lambda$, set it equal to zero, and solve for $\\lambda$:\n\n$$\\frac{d\\ell}{d\\lambda} = \\frac{n}{\\lambda} - \\sum_{i=1}^n t_i = 0$$ \n\nSolving for $\\lambda$ gives us:\n$$\\hat{\\lambda}_{\\text{MLE}} = \\frac{n}{\\sum_{i=1}^n t_i}$$  \n\n\nThis is the MLE estimate for the rate parameter of the exponential distribution based on our observed failure times. Notice that this estimate is simply the reciprocal of the sample mean of the failure times, which makes intuitive sense given the properties of the exponential distribution. We can verify that this critical point is indeed a maximum by checking the second derivative of the log-likelihood function evaluated at $\\hat{\\lambda}_{\\text{MLE}}$:\n\n$$\\frac{d^2\\ell}{d\\lambda^2} = -\\frac{n}{\\lambda^2}$$ \n\nwhich is negative for all $\\lambda > 0$. Therefore, we have a maximum at $\\hat{\\lambda}_{\\text{MLE}}$. In fact, the (only) critical point we find is a global maximum. \n\nFor a vector of parameters $\\boldsymbol{\\theta}$ with components $\\theta_1, \\theta_2, \\ldots, \\theta_p$, the MLE process is similar but we take the gradient of the log-likelihood with respect to the vector of parameters and set it equal to the zero vector to find the critical points. We can then use the Hessian matrix to check whether we have a maximum, minimum, or saddle point. For instance, the Weibull distribution has two parameters, the shape $\\gamma$ and the scale $\\theta$. The MLE process would involve taking the gradient of the log-likelihood with respect to both $\\gamma$ and $\\theta$, setting it equal to zero, and solving for both parameters simultaneously. Let's derive the MLE equations for the Weibull distribution. Suppose you have a dataset of failure times $t_1, t_2, \\ldots, t_n$ that you believe follows a Weibull distribution with shape parameter $\\gamma$ and scale parameter $\\theta$. The pdf of the Weibull distribution is given by:\n\n$$f(t ; \\gamma, \\theta) = \\frac{\\gamma}{\\theta} \\left( \\frac{t}{\\theta} \\right)^{\\gamma - 1} e^{-(t/\\theta)^\\gamma}$$\n\nThe likelihood function for the Weibull distribution is:\n\n$$L(\\gamma, \\theta) = \\prod_{i=1}^n \\frac{\\gamma}{\\theta} \\left( \\frac{t_i}{\\theta} \\right)^{\\gamma - 1} e^{-(t_i/\\theta)^\\gamma}$$\n\nThe log-likelihood function is:\n\n$$\\ell(\\gamma, \\theta) = n\\log\\gamma - n\\gamma\\log\\theta + (\\gamma - 1)\\sum_{i=1}^n \\log t_i - \\sum_{i=1}^n \\left(\\frac{t_i}{\\theta}\\right)^\\gamma$$\n\nTo find the MLE estimates $\\hat{\\gamma}$ and $\\hat{\\theta}$, we take the gradient of $\\ell(\\gamma, \\theta)$ with respect to both parameters, set it equal to zero, and solve for $\\gamma$ and $\\theta$. This will give us a system of equations that we can solve numerically to find the MLE estimates. The resulting equations are nonlinear and do not have a closed-form solution, which is why we need numerical optimization methods to find the MLE estimates for the Weibull distribution. We will see how to do this in practice using `lifelines` in the simulation below. \n\n::: {#cell-fig-weibull-mle .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nfrom lifelines import WeibullFitter\nimport matplotlib.pyplot as plt\n\n# Generate synthetic Weibull data\nnp.random.seed(42)\ntrue_gamma = 2.0   # shape\ntrue_theta = 100.0  # scale\nn = 200  # number of samples\n\n# Weibull random samples using inverse CDF\nu = np.random.uniform(0, 1, n)\nt = true_theta * (-np.log(1 - u))**(1/true_gamma)\n\n# All observed (no censoring yet)\nevent_observed = np.ones(n)\n\n# Fit\nwf = WeibullFitter()\nwf.fit(t, event_observed=event_observed)\nwf.print_summary()\n```\n\n::: {#fig-weibull-mle .cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <tbody>\n    <tr>\n      <th>model</th>\n      <td>lifelines.WeibullFitter</td>\n    </tr>\n    <tr>\n      <th>number of observations</th>\n      <td>200</td>\n    </tr>\n    <tr>\n      <th>number of events observed</th>\n      <td>200</td>\n    </tr>\n    <tr>\n      <th>log-likelihood</th>\n      <td>-1035.10</td>\n    </tr>\n    <tr>\n      <th>hypothesis</th>\n      <td>lambda_ != 1, rho_ != 1</td>\n    </tr>\n  </tbody>\n</table>\n</div><table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th style=\"min-width: 12px;\"></th>\n      <th style=\"min-width: 12px;\">coef</th>\n      <th style=\"min-width: 12px;\">se(coef)</th>\n      <th style=\"min-width: 12px;\">coef lower 95%</th>\n      <th style=\"min-width: 12px;\">coef upper 95%</th>\n      <th style=\"min-width: 12px;\">cmp to</th>\n      <th style=\"min-width: 12px;\">z</th>\n      <th style=\"min-width: 12px;\">p</th>\n      <th style=\"min-width: 12px;\">-log2(p)</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>lambda_</th>\n      <td>97.18</td>\n      <td>3.63</td>\n      <td>90.06</td>\n      <td>104.29</td>\n      <td>1.00</td>\n      <td>26.50</td>\n      <td>&lt;0.005</td>\n      <td>511.45</td>\n    </tr>\n    <tr>\n      <th>rho_</th>\n      <td>1.99</td>\n      <td>0.11</td>\n      <td>1.78</td>\n      <td>2.21</td>\n      <td>1.00</td>\n      <td>8.93</td>\n      <td>&lt;0.005</td>\n      <td>60.96</td>\n    </tr>\n  </tbody>\n</table><br><div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <tbody>\n    <tr>\n      <th>AIC</th>\n      <td>2074.19</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n`lifelines` uses `lambda_` for the scale parameter $\\theta$ and `rho_` for the \nshape parameter $\\gamma$ — different notation, same parameters. With $n = 200$ \nobservations, the estimated parameters are already close to the true values:\n\n$$\\hat{\\gamma} = 1.99 \\approx 2.0 = \\gamma_{\\text{true}}, \\qquad \\hat{\\theta} = 97.18 \\approx 100.0 = \\theta_{\\text{true}}$$\n\nMLE recovers the true parameters with high accuracy even at modest sample sizes.\n\n::: {#cell-fig-weibull-fit .cell execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![Fitted Weibull survival curve vs empirical survival curve](index_files/figure-html/fig-weibull-fit-output-1.png){#fig-weibull-fit width=853 height=470}\n:::\n:::\n\n\nThe fitted Weibull survival curve (gold) closely tracks the empirical survival \nfunction (blue) across the entire time range. The empirical survival function \nis simply the fraction of systems still surviving at each time point — no \ndistributional assumptions, just the raw data speaking for itself. The fact \nthat the fitted curve hugs it so tightly tells us two things: MLE found good \nparameter estimates, and the Weibull is a reasonable model for this data. We \nwill make this \"goodness of fit\" assessment more rigorous later using diagnostic \ntools.\n\nBut there is a catch — this was the easy case. All 200 observations were exact \nfailure times. In practice, not all machines will have failed by the end of the \nstudy — some will still be running when the study ends. How do we modify the \nlikelihood function to account for censoring? This is the key question that makes \nsurvival analysis different from classical statistical inference. We derive the censored likelihood function \nfrom first principles next.\n\n### MLE with Censored Data\n\nRemember that in survival analysis, we often have censored data — we know that a system survived up to a certain time, but we don't know the exact failure time. This is called right-censoring. We need to modify our likelihood function to account for this type of data. Recall from Part 1 of the series that we observe pairs of the form $(Y_i, \\delta_i)$ where $Y_i = \\min(T_i, C_i)$ is the observed time (either failure time or censoring time) and $\\delta_i$ is an indicator variable that is 1 if the event (failure) was observed and 0 if it was censored. If $\\delta_i = 1$, we know that the failure time $T_i$ was observed and is equal to $Y_i$. If $\\delta_i = 0$, we know that the system survived up to time $Y_i$, but we don't know the exact failure time. \n\nA brief notational remark before we proceed further. $T_i$ and $C_i$ are random variables representing \nthe (unknown) failure time and censoring time of the $i$-th unit. Their \nrealizations — the actual observed values — are denoted $t_i$ and $c_i$ \nin lowercase. $Y_i = \\min(T_i, C_i)$ is also a random variable, and its \nrealization is $y_i = \\min(t_i, c_i)$. We use uppercase for random variables \nand lowercase for their observed values throughout.\n\nHow does this affect the likelihood function? For an observed failure time (when $\\delta_i = 1$), the contribution to the likelihood is simply the pdf evaluated at $Y_i$: $f(y_i ; \\theta)$. This is equal to the pdf evaluated at the failure time $t_i$.\n\nFor a censored observation (when $\\delta_j = 0$), the observation tells us that \nthe failure time $T_j$ is greater than $Y_j$. The contribution to the likelihood \nis the probability that the system survived past $Y_j$, which is given by the \nsurvival function: $S(Y_j ; \\theta) = P(T_j > Y_j)$.\n\nThe full likelihood function for a dataset with both exact failure times and censored observations is the product of the contributions from all observations:\n\n$$L(\\theta) = \\prod_{i=1}^n [f(y_i ; \\theta)]^{\\delta_i} [S(y_i ; \\theta)]^{1 - \\delta_i}$$ \n\nYou might be wondering why we have the exponents $\\delta_i$ and $1 - \\delta_i$ in the likelihood function. This is a common way to write the likelihood function in survival analysis to compactly represent both types of observations. When $\\delta_i = 1$, the term $[f(y_i ; \\theta)]^{\\delta_i}$ becomes $f(y_i ; \\theta)$ and the term $[S(y_i ; \\theta)]^{1 - \\delta_i}$ becomes 1, so the contribution to the likelihood is just $f(y_i ; \\theta)$. When $\\delta_j = 0$, the term $[f(y_j ; \\theta)]^{\\delta_j}$ becomes 1 and the term $[S(y_j ; \\theta)]^{1 - \\delta_j}$ becomes $S(y_j ; \\theta)$, so the contribution to the likelihood is just $S(y_j ; \\theta)$. This way of writing the likelihood function allows us to handle both types of observations in a unified framework. This is very similar to writing the likelihood function (or loss function) in logistic regression, where we have a binary outcome and we use the observed labels to determine which term contributes to the likelihood for each observation.\n\nFinally, a point worth observing is that the likelihood function for censored data is not a simple product of pdfs, but rather a product of a mixture of pdfs and survival functions. How can you combine the PDF (which is a density) and the survival function (which is a probability) in the same likelihood function? The answer lies in the fact that we are not comparing incompatible objects. For a censored observation, $S(y_j;\\theta) = P(T_j > y_j)$ is a genuine probability. For an exact failure, $f(y_i;\\theta)$ is a density — but both contribute to the same likelihood because we are asking the same question for each observation: what \nparameter value $\\theta$ makes this observation most plausible? The likelihood function combines these two types of contributions in a unified framework that allows MLE to work even in the presence of censoring.\n\nIf you want to be very abstract and not make a big deal about the fact that we are mixing densities and probabilities, you can just think of the likelihood function as a product of two functions and you are trying to find the parameter values that maximize this product. The abstract view strips away the details and allows you to focus on the optimization problem. However, it has a disadvantage that it takes away the intuition about why we are using the pdf for exact failures and the survival function for censored observations. The more concrete view emphasizes the different contributions to the likelihood from different types of observations, which can help build intuition about how MLE works in the presence of censoring. Both views are valid and can be useful in different contexts.\n\nLet's spend some more time on understanding true failure $\\delta = 1$ vs censoring $\\delta = 0$ and how they contribute to the likelihood function a little more intuitively. \n\nCase 1: **$\\delta_i = 1$ (exact failure observed)**. \n\nIn this case, we know that the **observed** failure time $t_i$ (a realization of $T_i$) is less than or equal to the censoring time $C_i$. Consider the event that the failure time $T_i \\leq C_i$ and the failure time is in a small interval around $t_i$. If the censoring time $C_i$ and the failure time $T_i$ are independent, then the joint probability of observing a failure at time $t_i$ and it being uncensored can be expressed as:\n\n$$P(T_i \\in [t_i, t_i + \\Delta t], T_i \\leq C_i) = P(T_i \\in [t_i, t_i + \\Delta t]) \\cdot P(C_i \\geq t_i)$$\nThe first term $P(T_i \\in [t_i, t_i + \\Delta t])$ is approximately equal to the pdf evaluated at $t_i$: $f(t_i ; \\theta) \\Delta t$. The second term $P(C_i \\geq t_i)$ is the probability that the censoring time is greater than or equal to $t_i$, which is given by the survival function of the censoring distribution evaluated at $t_i$: $S_C(t_i)$. Therefore, the contribution to the likelihood from an exact failure observation can be expressed as:\n\n$$P(T_i \\in [t_i, t_i + \\Delta t], T_i \\leq C_i) = f(t_i ; \\theta) \\, \\Delta t \\cdot S_C(t_i)$$\n\nSince we are maximizing the likelihood with respect to $\\theta$, the term $S_C(t_i)$ does not depend on $\\theta$ and can be treated as a constant. Therefore, the contribution to the likelihood from an exact failure observation is effectively proportional to the pdf evaluated at $t_i$: $f(t_i ; \\theta)$. This is why we use the pdf for exact failure observations in the likelihood function. Note that the term $S_C(t_i)$ is the survival function of the censoring distribution, which represents the probability that the censoring time is greater than or equal to $t_i$ and therefore has nothing to do with the failure parameters $\\theta$ that we are trying to estimate. \n\nCase 2: **$\\delta_j = 0$ (censored observation)**.\n\nIn this case, we know that the system survived up to time $y_j$, but we don't know the exact failure time. The contribution to the likelihood from a censored observation is the probability that the failure time $T_j$ is greater than $y_j$: $P(T_j > y_j) = S(y_j ; \\theta)$. We know with certainty that the system survived up to time $y_j$, so the likelihood contribution is the probability of surviving past that time, which is given by the survival function. Consider the event that the failure time $T_j$ is greater than $y_j$ and the censoring time $C_j$ is in a small interval around $y_j$. If the censoring time $C_j$ and the failure time $T_j$ are independent, then the joint probability of observing a censored observation at time $y_j$ can be expressed as:\n\n$$P(T_j > y_j, C_j \\in [y_j, y_j + \\Delta t]) = P(T_j > y_j) \\cdot P(C_j \\in [y_j, y_j + \\Delta t])$$\n\nThe first term $P(T_j > y_j)$ is the probability that the failure time is greater than $y_j$, which is given by the survival function evaluated at $y_j$: $S(y_j ; \\theta)$. The second term $P(C_j \\in [y_j, y_j + \\Delta t])$ is approximately equal to the pdf of the censoring distribution evaluated at $Y_j$: $f_C(y_j) \\Delta t$. Therefore, the contribution to the likelihood from a censored observation can be expressed as:\n\n$$P(T_j > y_j, C_j \\in [y_j, y_j + \\Delta t]) = S(y_j ; \\theta) \\cdot f_C(y_j) \\Delta t$$\n\nSince we are maximizing the likelihood with respect to $\\theta$, the term $f_C(Y_j) \\Delta t$ does not depend on $\\theta$ and can be treated as a constant. Therefore, the contribution to the likelihood from a censored observation is effectively proportional to the survival function evaluated at $Y_j$: $S(y_j ; \\theta)$. This is why we use the survival function for censored observations in the likelihood function. Note that the term $f_C(y_j) \\Delta t$ is the pdf of the censoring distribution, which represents the probability of observing a censoring event at time $Y_j$ and therefore has nothing to do with the failure parameters $\\theta$ that we are trying to estimate.\n\nCombining both cases and all the observations, the full censored likelihood is:\n\n$$L(\\theta) = \\prod_{i=1}^n [f(y_i ; \\theta)]^{\\delta_i} [S(y_i ; \\theta)]^{1 - \\delta_i}$$\n\nwhere the $\\Delta t$ and censoring distribution terms have been absorbed into \na proportionality constant that does not affect the location of the maximum.\n\nThe assumption of independence between the failure time and censoring time is crucial for this derivation. This is known as the **non-informative censoring assumption**, which tells us that knowing when a subject was censored does not give us any information about their failure time. This assumption is violated in some real world scenarios, such as when a machine operator decides to stop a machine that is showing signs of imminent failure, or when a patient drops out of a clinical trial due to worsening health. In such cases, the censoring is informative and the standard MLE approach may yield biased estimates. There are methods to handle informative censoring, such as joint modeling of the failure and censoring processes, but these are beyond the scope of this post.\n\n#### The Log-Likelihood Function with Censoring\n\nThe full censored likelihood function is: \n\n$$L(\\theta) = \\prod_{i=1}^n [f(y_i ; \\theta)]^{\\delta_i} [S(y_i ; \\theta)]^{1-\\delta_i}$$\n\nTaking the natural logarithm of the likelihood function gives us the log-likelihood function:\n\n$$\\ell(\\theta) = \\sum_{i=1}^n \\left[ \\delta_i \\log f(y_i ; \\theta) + (1 - \\delta_i) \\log S(y_i ; \\theta) \\right]$$\n\nBased on our previous study of the relationship between the pdf and the survival function, we can express the log-likelihood function in terms of the hazard function $\\lambda(t ; \\theta)$. Recall that the pdf can be expressed as $f(t ; \\theta) = \\lambda(t ; \\theta) S(t ; \\theta)$, so we can rewrite the log-likelihood function as: \n\n$$\\ell(\\theta) = \\sum_{i=1}^n \\left[ \\delta_i \\log \\lambda(y_i ; \\theta) + \\log S(y_i ; \\theta) \\right]$$\n\nNotice that $\\log S(y_i;\\theta)$ appears for **every** observation regardless \nof whether it failed or was censored — survival information contributes to the \nlikelihood for all units. The hazard term $\\delta_i \\log \\lambda(y_i;\\theta)$ \nonly contributes for observed failures. This is the elegance of the censored \nlikelihood. Finally, we can express the log-likelihood function in terms of the cumulative hazard function $\\Lambda(t ; \\theta)$ using the relationship $S(t ; \\theta) = e^{-\\Lambda(t ; \\theta)}$:\n\n$$\\ell(\\theta) = \\sum_{i=1}^n \\left[ \\delta_i \\log \\lambda(y_i ; \\theta) - \\Lambda(y_i ; \\theta) \\right]$$\n\nNow we use our calculus machinery to find the MLE estimates. Taking the derivative of the log-likelihood function with respect to $\\theta$ and setting it equal to zero gives us the MLE equations that we can solve to find the parameter estimates. The specific forms of these equations will depend on the distribution we are fitting. And sometimes, these equations will be so nonlinear and complex that we won't be able to solve them analytically. We will see how to handle this in practice using numerical optimization methods in `lifelines` when we fit the Weibull distribution with censored data in the next section.\n\nBut first, let's calculate the analytical MLE estimates for the exponential distribution with censored data to see how the presence of censoring modifies the MLE equations. The exponential distribution has a single parameter $\\lambda$ (the rate), and its pdf and survival function are given by:\n\n$$f(t ; \\lambda) = \\lambda e^{-\\lambda t}$$\n$$S(t ; \\lambda) = e^{-\\lambda t}$$\n\nThe log-likelihood function for the exponential distribution with censored data is:\n\n$$\\ell(\\lambda) = \\sum_{i=1}^n \\left[ \\delta_i \\log (\\lambda e^{-\\lambda y_i}) + (1 - \\delta_i) \\log (e^{-\\lambda y_i}) \\right]$$\n\nThis simplifies to:\n\n$$\\ell(\\lambda) = \\sum_{i=1}^n \\left[ \\delta_i \\log \\lambda - \\lambda y_i \\right]$$\n\nTaking the derivative of the log-likelihood function with respect to $\\lambda$ and setting it equal to zero gives us:\n\n$$\\frac{d\\ell}{d\\lambda} = \\sum_{i=1}^n \\left[ \\frac{\\delta_i}{\\lambda} - y_i \\right] = 0$$\n\nSolving for $\\lambda$ gives us the MLE estimate for the exponential distribution with censored data:\n\n$$\\hat{\\lambda}_{\\text{MLE}} = \\frac{\\sum_{i=1}^n \\delta_i}{\\sum_{i=1}^n y_i}$$\n\nThe quantity $\\sum_{i=1}^n y_i$ is known as the **total time at risk**, which is the sum of the observed times for all units, regardless of whether they failed or were censored. Each unit contributes to the total time at risk based on its observed duration. The quantity $\\sum_{i=1}^n \\delta_i$ is the total number of observed failures.\n\nIsn't this marvelous? The MLE estimate for the rate parameter $\\lambda$ in the presence of censoring is simply the total number of observed failures (the sum of $\\delta_i$) divided by the total time at risk (the sum of $y_i$). If the data were fully observed with no censoring, then $\\sum_{i=1}^n \\delta_i = n$ and we would recover the MLE estimate for the exponential distribution without censoring: $\\hat{\\lambda}_{\\text{MLE}} = \\frac{n}{\\sum_{i=1}^n y_i}$ (I have used $y_i$ instead of $t_i$ for consistency with the current topic). The presence of censoring effectively reduces the number of observed failures and increases the total time at risk, which leads to a different MLE estimate that accounts for the incomplete information in the data. This is the power of the censored likelihood function — it allows us to make valid inferences about the parameters of the failure distribution even when we have incomplete data due to censoring. It is left an exercise for the reader to verify that the MLE estimate for the exponential distribution with censored data is indeed a maximum by checking the second derivative of the log-likelihood function evaluated at $\\hat{\\lambda}_{\\text{MLE}}$. \n\n#### MLE with Censoring: A synthetic data example \n\nRather than working with abstract numbers and symbols, let's build a dataset that will accompany us for the rest of the series- a synthetic fleet of 1000 machines, each with its own age, operating conditions, and failure history. \n\n::: {#dataset-generation .cell execution_count=3}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport os\n\nnp.random.seed(42)\nn = 1000\n\n# --- Continuous covariates ---\nmachine_age        = np.random.uniform(0, 15, n)\nusage_intensity    = np.random.uniform(0.5, 2.0, n)\noperating_temp     = np.random.uniform(60, 120, n)\nload_factor        = np.random.uniform(0.3, 1.0, n)\nrpm                = np.random.uniform(500, 3000, n)\nvibration_level    = np.random.uniform(0.5, 10, n)\noil_quality        = np.random.uniform(0, 1, n)\nmaintenance_count  = np.random.randint(0, 21, n).astype(float)\n\n# --- Categorical covariates ---\nenvironment  = np.random.choice(['indoor', 'outdoor', 'harsh'], n, p=[0.4, 0.4, 0.2])\nmanufacturer = np.random.choice(['A', 'B', 'C'], n, p=[0.4, 0.35, 0.25])\n\n# --- Encode categoricals for survival time generation ---\nenv_effect = np.where(environment == 'indoor', 1.0,\n             np.where(environment == 'outdoor', 0.85, 0.65))\n\nmfr_effect = np.where(manufacturer == 'A', 1.0,\n             np.where(manufacturer == 'B', 0.9, 0.75))\n\n# --- True Weibull parameters ---\n# Scale theta depends on covariates\n# Higher stress covariates -> smaller theta -> shorter survival\ngamma_true = 2.0\n\ntheta_true = (\n    300\n    * env_effect\n    * mfr_effect\n    / (\n        1\n        + 0.03 * machine_age\n        + 0.15 * usage_intensity\n        + 0.008 * operating_temp\n        + 0.10 * load_factor\n        + 0.0001 * rpm\n        + 0.05 * vibration_level\n        + 0.10 * oil_quality\n        - 0.02 * maintenance_count  # more maintenance -> longer survival\n    )\n)\n\n# --- Generate Weibull failure times via inverse CDF ---\nu = np.random.uniform(0, 1, n)\nT = theta_true * (-np.log(1 - u))**(1 / gamma_true)\n\n# --- Random right censoring ---\nC = np.random.uniform(50, 400, n)\n\n# --- Observed time and event indicator ---\nY     = np.minimum(T, C)\ndelta = (T <= C).astype(int)\n\n# --- Build dataframe ---\ndf = pd.DataFrame({\n    'machine_id':         [f'M{i+1:04d}' for i in range(n)],\n    'machine_age':        machine_age.round(2),\n    'usage_intensity':    usage_intensity.round(2),\n    'operating_temp':     operating_temp.round(2),\n    'load_factor':        load_factor.round(2),\n    'rpm':                rpm.round(0).astype(int),\n    'vibration_level':    vibration_level.round(3),\n    'oil_quality':        oil_quality.round(3),\n    'maintenance_count':  maintenance_count.astype(int),\n    'environment':        environment,\n    'manufacturer':       manufacturer,\n    'observed_time':      Y.round(2),\n    'event_observed':     delta\n})\n\n# --- Summary ---\nprint(f\"Total machines    : {n}\")\nprint(f\"Observed failures : {delta.sum()} ({100*delta.mean():.1f}%)\")\nprint(f\"Censored          : {(1-delta).sum()} ({100*(1-delta).mean():.1f}%)\")\nprint(f\"Mean observed time: {Y.mean():.1f} hours\")\nprint(f\"\\nFirst 10 rows:\")\nprint(df.head(10).to_string(index=False))\n\n# --- Save ---\nos.makedirs('../../data', exist_ok=True)\ndf.to_csv('../../data/machine_fleet.csv', index=False)\nprint(\"\\nDataset saved to ../../data/machine_fleet.csv\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTotal machines    : 1000\nObserved failures : 886 (88.6%)\nCensored          : 114 (11.4%)\nMean observed time: 81.4 hours\n\nFirst 10 rows:\nmachine_id  machine_age  usage_intensity  operating_temp  load_factor  rpm  vibration_level  oil_quality  maintenance_count environment manufacturer  observed_time  event_observed\n     M0001         5.62             0.78           75.70         0.77 1930            4.240        0.648                 10     outdoor            A         111.39               1\n     M0002        14.26             1.31           74.82         0.86 2514            4.998        0.172                 16     outdoor            A          68.56               1\n     M0003        10.98             1.81          114.38         0.48 2400            8.618        0.872                  4      indoor            C          49.03               1\n     M0004         8.98             1.60           74.97         0.74  885            3.730        0.613                  6       harsh            A          88.65               1\n     M0005         2.34             1.71           76.32         0.70  873            8.762        0.157                 18      indoor            B         205.67               1\n     M0006         2.34             1.49          105.56         0.88 1170            1.337        0.962                 14       harsh            B          69.69               1\n     M0007         0.87             1.54           86.98         0.93 1403            7.880        0.518                  2     outdoor            B          79.77               0\n     M0008        12.99             1.77          106.60         0.31 1521            8.552        0.073                 14      indoor            B          28.99               1\n     M0009         9.02             0.87           63.92         0.77 2199            2.227        0.627                  4       harsh            B          37.09               1\n     M0010        10.62             1.23           89.25         0.34  642            4.588        0.253                 11      indoor            A         106.60               1\n\nDataset saved to ../../data/machine_fleet.csv\n```\n:::\n:::\n\n\nWe generate a synthetic fleet of 1000 machines, each with 8 continuous and 2 \ncategorical covariates representing realistic machine characteristics — age, \noperating temperature, vibration level, manufacturer, and so on. The true \nfailure times are drawn from a Weibull distribution with shape $\\gamma = 2.0$ \nand a scale parameter $\\theta$ that depends on the covariates — higher stress \n(temperature, vibration, load) shrinks $\\theta$ and shortens expected lifetime, \nwhile more maintenance history extends it.\n\nFor now, we work only with the observed times — whether the machine failed or \nwas censored. But in reality, a machine's lifetime depends on its physical \ncharacteristics — how old it is, how hard it runs, the temperature it operates \nat, how well it has been maintained. Modeling the relationship between these \ncharacteristics and the failure time is exactly what survival regression models \nlike the Cox Proportional Hazards model are built to do — and that is where we \nare headed.\n\nNow, we will fit a Weibull to the observed times with `lifelines`. Here is the piece of code. \n\n::: {#cell-weibull-fit-censored .cell execution_count=4}\n``` {.python .cell-code}\nimport pandas as pd\nfrom lifelines import WeibullFitter\n\nwf = WeibullFitter()\ndf = pd.read_csv('../../data/machine_fleet.csv')\n\nwf.fit(df['observed_time'], event_observed=df['event_observed'])\nwf.print_summary()\n```\n\n::: {#weibull-fit-censored .cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <tbody>\n    <tr>\n      <th>model</th>\n      <td>lifelines.WeibullFitter</td>\n    </tr>\n    <tr>\n      <th>number of observations</th>\n      <td>1000</td>\n    </tr>\n    <tr>\n      <th>number of events observed</th>\n      <td>886</td>\n    </tr>\n    <tr>\n      <th>log-likelihood</th>\n      <td>-4684.21</td>\n    </tr>\n    <tr>\n      <th>hypothesis</th>\n      <td>lambda_ != 1, rho_ != 1</td>\n    </tr>\n  </tbody>\n</table>\n</div><table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th style=\"min-width: 12px;\"></th>\n      <th style=\"min-width: 12px;\">coef</th>\n      <th style=\"min-width: 12px;\">se(coef)</th>\n      <th style=\"min-width: 12px;\">coef lower 95%</th>\n      <th style=\"min-width: 12px;\">coef upper 95%</th>\n      <th style=\"min-width: 12px;\">cmp to</th>\n      <th style=\"min-width: 12px;\">z</th>\n      <th style=\"min-width: 12px;\">p</th>\n      <th style=\"min-width: 12px;\">-log2(p)</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>lambda_</th>\n      <td>97.26</td>\n      <td>1.80</td>\n      <td>93.72</td>\n      <td>100.79</td>\n      <td>1.00</td>\n      <td>53.41</td>\n      <td>&lt;0.005</td>\n      <td>inf</td>\n    </tr>\n    <tr>\n      <th>rho_</th>\n      <td>1.86</td>\n      <td>0.05</td>\n      <td>1.76</td>\n      <td>1.95</td>\n      <td>1.00</td>\n      <td>17.69</td>\n      <td>&lt;0.005</td>\n      <td>230.18</td>\n    </tr>\n  </tbody>\n</table><br><div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <tbody>\n    <tr>\n      <th>AIC</th>\n      <td>9372.42</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n886 out of 1000 machines failed during the study- an 88.6% event rate with 11.4% censored. The fitted shape parameter $\\hat{\\gamma} = 1.86$ is close to \nbut not exactly the true value of $\\gamma = 2.0$. This is expected — we are \nfitting a single Weibull to all 1000 machines while ignoring the fact that each \nmachine has a different $\\theta$ driven by its covariates. By fitting a single Weibull, we are forcing one distribution to describe a heterogeneous fleet of machines. This is precisely why survival regression methods exist- to model how machine characteristics influence lifetime. We will get there eventually. But first, let's assess how well this naive fit describes the data using diagnostic tools. \n\n### Diagnostic Tool: Q-Q Plot \n\nThe Q-Q plot is a graphical method to display whether a dataset follows a particular distribution or whether two datasets come from the same population. For our purposes, we are testing if the dataset comes from a particular Weibull or not. Note that the game is rigged- we simulated data to follow a particular Weibull, so we already know the answer. But the Q-Q plot is a diagnostic tool we will use repeatedly on real data where we do not know the answer. \n\nThe basic idea of the Q-Q plot is to compare theoretical quantiles vs empirical quantiles. If the data fits a particular Weibull, these quantiles should match and the points should fall on a straight line. Here is how we'll build the Q-Q plot for the Weibull step by step. \n\n#### Step 1: Theoretical Quantiles\n\nRecall that the $p$-th quantile of a probability distribution is the value $t_p$ \nsuch that $P(T \\leq t_p) = p$ where $p \\in [0, 1]$. For instance, the 0.5 quantile \n(also called the 50th percentile) is the median. Let's derive the theoretical \nquantiles of the Weibull distribution.\n\nWe want to find $t_p$ such that $F(t_p) = p$. If $T \\sim \\text{Weibull}(\\theta, \\gamma)$, \nthen:\n\n$$1 - \\exp\\left\\{-\\left(\\frac{t_p}{\\theta}\\right)^\\gamma\\right\\} = p$$\n\nRearranging:\n\n$$1 - p = \\exp\\left\\{-\\left(\\frac{t_p}{\\theta}\\right)^\\gamma\\right\\}$$\n\nTaking logarithms of both sides:\n\n$$-\\ln(1-p) = \\left(\\frac{t_p}{\\theta}\\right)^\\gamma$$\n\n$$\\ln\\left(\\frac{1}{1-p}\\right) = \\left(\\frac{t_p}{\\theta}\\right)^\\gamma$$\n\nTaking the $\\gamma$-th root:\n\n$$\\boxed{t_p = \\theta \\left[\\ln\\left(\\frac{1}{1-p}\\right)\\right]^{1/\\gamma}}$$\n\nThis is the quantile function (inverse CDF) of the Weibull distribution. Given \na probability $p$, it tells us the time by which a fraction $p$ of systems are \nexpected to have failed.\n\nHere is a special value: $p = 1 - \\frac{1}{e}$. Substituting into the quantile function:\n\n$$t_p = \\theta \\left[\\ln\\left(\\frac{1}{1-(1-\\frac{1}{e})}\\right)\\right]^{1/\\gamma} = \\theta \\left[\\ln\\left(\\frac{1}{\\frac{1}{e}}\\right)\\right]^{1/\\gamma} = \\theta \\left[\\ln(e)\\right]^{1/\\gamma} = \\theta \\cdot 1^{1/\\gamma} = \\theta$$\n\nSo $t_{1-1/e} = \\theta$ — the scale parameter $\\theta$ is exactly the $(1 - 1/e) \\approx 63.2$th \npercentile of the Weibull distribution, regardless of the shape parameter $\\gamma$. \nThis confirms what we noted earlier: by time $\\theta$, approximately 63.2% of \nsystems will have failed.\n\n\n#### Step 2: Empirical Quantiles\n\nThe empirical quantiles are the ones you get directly from your dataset. \n\n**Step 2a: Sort your data.** Arrange the observed failure times in ascending order:\n\n$$t_{(1)} \\leq t_{(2)} \\leq \\cdots \\leq t_{(n)}$$\n\nThe notation $t_{(i)}$ denotes the $i$-th order statistic — $t_{(1)}$ is the \nsmallest observed failure time, $t_{(2)}$ is the next smallest, and $t_{(n)}$ \nis the largest.\n\n**Step 2b: Assign plotting positions.** The $i$-th order statistic $t_{(i)}$ \ncorresponds to an approximate quantile level:\n\n$$\\hat{p}_i = \\frac{i - 0.3}{n + 0.4}$$\n\nThis is known as the **median rank formula** (Benard's approximation, 1953). It \nestimates the probability level associated with the $i$-th smallest observation. \nThe corrections $-0.3$ and $+0.4$ reduce bias compared to the naive estimate \n$\\hat{p}_i = i/n$, particularly in the tails of the distribution.\n\n#### Step 3: Constructing the Q-Q Plot\n\n**Step 3a:** Fit the Weibull distribution to get the estimated parameters \n$\\hat{\\gamma}$ and $\\hat{\\theta}$.\n\n**Step 3b:** For each data point $i = 1, 2, \\ldots, n$:\n\n- The empirical quantile is $t_{(i)}$ — the $i$-th ordered failure time from \nthe data.\n- The approximate quantile level is $\\hat{p}_i = \\frac{i - 0.3}{n + 0.4}$ \nfrom the median rank formula.\n- The theoretical quantile is:\n\n$$q_{\\hat{p}_i} = \\hat{\\theta}\\left[\\ln\\left(\\frac{1}{1 - \\hat{p}_i}\\right)\\right]^{1/\\hat{\\gamma}}$$\n\n**Step 3c:** Plot the pairs $(q_{\\hat{p}_i},\\ t_{(i)})$ for each $i = 1, 2, \\ldots, n$.\n\n**What to look for:**\n\n- **Straight line through the origin with slope 1** — perfect fit. The theoretical \nand empirical quantiles agree at every probability level.\n- **Points above the diagonal** — the data has heavier tails than the Weibull \npredicts. Some machines lasted much longer than expected.\n- **Points below the diagonal** — the data has lighter tails than the Weibull \npredicts. Failures are happening earlier than the model expects.\n- **S-shaped curve** — the data comes from a mixed distribution or the shape \nparameter $\\gamma$ is wrong.\n\nWe will make these observations more precise and illuminating with a worked \nexample shortly. Do not panic. For now we construct the Q-Q plot using only the observed failures, ignoring censored observations. This is a simplification — a more rigorous approach uses the Kaplan-Meier estimator for the empirical quantiles, which we will introduce in Part 4.\n\nLet's see how well our fitted Weibull describes the machine fleet data. Here is the Q-Q plot using the 886 observed failures.\n\n::: {#cell-fig-qqplot-fleet .cell execution_count=5}\n\n::: {.cell-output .cell-output-display}\n![Q-Q plot: fitted Weibull vs observed failure times (machine fleet)](index_files/figure-html/fig-qqplot-fleet-output-1.png){#fig-qqplot-fleet width=663 height=662}\n:::\n:::\n\n\nThe Q-Q plot tells a clear story. Most points fall below the $y = x$ diagonal — the empirical quantiles are \nsmaller than the theoretical quantiles at the same probability level i.e $t_{(i)} < q_{\\hat{p}_i}$. What does that mean mathematically? Since the CDF $F$ is monotone increasing, this implies:\n\n$$F(t_{(i)}) < F(q_{\\hat{p}_i}) = \\hat{p}_i \\quad \\Longleftrightarrow \\quad S(t_{(i)}) > 1 - \\hat{p}_i$$\n\nThe fitted Weibull assigns too high a survival probability at the actual observed failure times- it thinks more machines should still be running than actually are. In simple words: the Weibull estimator is too optimistic. It predicts machines will last longer than they actually do. \n\nThis is the signature of a heterogeneous fleet being forced into a single distribution. Each machine has its own true $\\theta$ driven by its covariates like usage, age, temperature etc. A single Weibull cannot capture all of that simultaneously, and the Q-Q plot is telling us exactly that. This is precisely why survival regression exists and we will explore that in the later modules. \n\n::: {.callout-note collapse=\"true\"}\n## A note on other Q-Q plot patterns\n\n- **Points above the diagonal** — $t_{(i)} > q_{\\hat{p}_i}$, which implies \n$F(t_{(i)}) > \\hat{p}_i$ and $S(t_{(i)}) < 1 - \\hat{p}_i$. The Weibull \nunderestimates survival — it predicts more failures by time $t_{(i)}$ than \nactually occurred. The data has heavier tails than the model expects.\n\n- **S-shaped curve** — points below the diagonal in the lower tail and above \nin the upper tail (or vice versa). The shape parameter $\\gamma$ is likely \nmisspecified, or the data comes from a mixture of two distinct populations \nwith different failure regimes.\n:::\n\n\n### Empirical CDF and the Binomial Connection\n\nI cannot help but talk about a beautiful connection between the empirical CDF \nand the Binomial distribution. Here is how it goes.\n\nGiven data $t_1, t_2, \\ldots, t_n$, the empirical CDF estimates the true CDF \nfrom the data alone — no distributional assumptions, no parameters to fit. For \nany time $t$:\n\n$$\\hat{F}_n(t) = \\frac{\\text{number of observations} \\leq t}{n}$$\n\nUsing indicator notation, this can be written compactly as:\n\n$$\\hat{F}_n(t) = \\frac{1}{n} \\sum_{i=1}^{n} \\mathbf{1}\\{t_i \\leq t\\}$$\n\nwhere $\\mathbf{1}\\{t_i \\leq t\\}$ is 1 if the $i$-th observation is less than \nor equal to $t$, and 0 otherwise.\n\n::: {.callout-note collapse=\"true\"}\n## Indicator Notation\nThe indicator function $\\mathbf{1}\\{A\\}$ for an event $A$ is defined as:\n\n$$\\mathbf{1}\\{A\\} = \\begin{cases} 1 & \\text{if } A \\text{ occurs} \\\\ 0 & \\text{otherwise} \\end{cases}$$\n\nAn equivalent notation uses a set $A$ and a point $x$:\n\n$$\\mathbf{1}_A(x) = \\begin{cases} 1 & \\text{if } x \\in A \\\\ 0 & \\text{otherwise} \\end{cases}$$\n\nIn our case, $\\mathbf{1}\\{t_i \\leq t\\}$ is shorthand for $\\mathbf{1}_{(-\\infty, t]}(t_i)$ \n— it equals 1 if the observation $t_i$ falls in the set $(-\\infty, t]$, and 0 otherwise.\n:::\n\nHere is a simple example. Consider five observed failure times: \n$t_1 = 200,\\ t_2 = 350,\\ t_3 = 400,\\ t_4 = 550,\\ t_5 = 600$ hours.\n\n- For $t < 200$: no failures yet, so $\\hat{F}_5(t) = 0$\n- For $200 \\leq t < 350$: one failure observed, so $\\hat{F}_5(t) = \\frac{1}{5} = 0.20$\n- For $350 \\leq t < 400$: two failures observed, so $\\hat{F}_5(t) = \\frac{2}{5} = 0.40$\n- For $400 \\leq t < 550$: three failures observed, so $\\hat{F}_5(t) = \\frac{3}{5} = 0.60$\n- For $550 \\leq t < 600$: four failures observed, so $\\hat{F}_5(t) = \\frac{4}{5} = 0.80$\n- For $t \\geq 600$: all five failures observed, so $\\hat{F}_5(t) = \\frac{5}{5} = 1.0$\n\nThe empirical CDF is a step function — it jumps by $\\frac{1}{n}$ at each \nobserved failure time and stays flat in between. Here is a plot showing the empirical CDF with these examples.\n\n::: {#cell-fig-ecdf-example .cell execution_count=6}\n\n::: {.cell-output .cell-output-display}\n![Empirical CDF for a simple example with 5 failure times](index_files/figure-html/fig-ecdf-example-output-1.png){#fig-ecdf-example width=756 height=470}\n:::\n:::\n\n\nEach jump represents one observed failure. The empirical CDF makes no assumptions \nabout the underlying distribution — it simply counts. This is what makes it so \npowerful as a diagnostic tool, and as you will see in Part 4, it is also the \nfoundation of the Kaplan-Meier estimator.\n\n#### The Binomial Connection\n\nFix a time value $t$. For the $i$-th observation, with corresponding random \nvariable $T_i$, define the indicator random variable:\n\n$$X_i = \\begin{cases} 1 & \\text{if } T_i \\leq t \\\\ 0 & \\text{otherwise} \\end{cases}$$\n\nSince $X_i$ is a random variable, it has an associated probability. What is \n$P(X_i = 1)$? It is simply the probability that $T_i \\leq t$, which is exactly \nthe CDF of $T_i$ evaluated at $t$:\n\n$$P(X_i = 1) = P(T_i \\leq t) = F(t)$$\n\nDoesn't this remind you of a coin toss? If we think of \"failure by time $t$\" \nas analogous to obtaining heads, then $F(t)$ plays the role of the probability \nof heads. The indicator $X_i$ is therefore a Bernoulli random variable with \nparameter $F(t)$:\n\n$$X_i \\sim \\text{Bernoulli}(F(t))$$\n\nNow let $X = \\sum_{i=1}^n X_i$. This counts the total number of observations \nthat have failed by time $t$. Since the failure times $T_1, T_2, \\ldots, T_n$ \nare independent and identically distributed, the indicators $X_1, X_2, \\ldots, X_n$ \nare independent Bernoulli$(F(t))$ random variables. A sum of $n$ independent \nBernoulli$(p)$ random variables follows a Binomial$(n, p)$ distribution, so:\n\n$$X \\sim \\text{Binomial}(n,\\ F(t))$$\n\nThe expectation and variance of $X$ are:\n\n$$E[X] = n \\cdot F(t), \\qquad \\text{Var}[X] = n \\cdot F(t) \\cdot (1 - F(t)) = n \\cdot F(t) \\cdot S(t)$$\n\n#### Connection with the Empirical CDF\n\nThe empirical CDF is:\n\n$$\\hat{F}_n(t) = \\frac{1}{n}\\sum_{i=1}^n \\mathbf{1}\\{t_i \\leq t\\} = \\frac{1}{n}\\sum_{i=1}^n X_i = \\frac{X}{n}$$\n\nSince $X \\sim \\text{Binomial}(n, F(t))$, we have:\n\n$$P(X = k) = \\binom{n}{k} [F(t)]^k [1 - F(t)]^{n-k}$$\n\n$X$ takes integer values $\\{0, 1, \\ldots, n\\}$, so $\\hat{F}_n(t) = X/n$ takes \nvalues $\\left\\{0, \\frac{1}{n}, \\frac{2}{n}, \\ldots, 1\\right\\}$ — and the \ndifference between consecutive values is exactly the jump size $\\frac{1}{n}$ \nwe observed in the step function plot. The probability that the empirical CDF \ntakes the value $k/n$ is:\n\n$$P\\left(\\hat{F}_n(t) = \\frac{k}{n}\\right) = P(X = k) = \\binom{n}{k} [F(t)]^k [1 - F(t)]^{n-k}$$\n\nThe moments of $\\hat{F}_n(t)$ follow directly from those of $X$:\n\n$$E[\\hat{F}_n(t)] = \\frac{E[X]}{n} = \\frac{n \\cdot F(t)}{n} = F(t)$$\n\n$$\\text{Var}[\\hat{F}_n(t)] = \\frac{\\text{Var}[X]}{n^2} = \\frac{n \\cdot F(t) \\cdot S(t)}{n^2} = \\frac{F(t) \\cdot S(t)}{n} = \\frac{F(t)(1 - F(t))}{n}$$\n\nTwo beautiful results — the empirical CDF is an **unbiased estimator** of the \ntrue CDF $F(t)$, and its variance shrinks as $n$ grows. The larger the dataset, \nthe more precisely $\\hat{F}_n(t)$ estimates $F(t)$ at every time point $t$.\n\n### The Kolmogorov-Smirnov (K-S) Test\n\nThe core idea of the K-S test is simple. You have two CDFs:\n\n- $\\hat{F}_n(t)$ — the empirical CDF, computed from the data\n- $F(t; \\hat{\\theta}, \\hat{\\gamma})$ — the fitted Weibull CDF\n\nAt every point $t$, these two curves have some vertical distance between them. \nThe K-S test statistic is simply the largest such distance:\n\n$$D_n = \\sup_t \\left|\\hat{F}_n(t) - F(t; \\hat{\\theta}, \\hat{\\gamma})\\right|$$\n\n$$D_n = \\|\\hat{F}_n - F(\\cdot\\, ;\\hat{\\theta}, \\hat{\\gamma})\\|_\\infty$$\n\n\nwhere $\\sup$ stands for supremum — the least upper bound of a set of real \nnumbers that's (at least) bounded above. (i.e., there exists some number $M$ such that \nevery element in the set is $\\leq M$. This number M is called an upper bound). The axiom of completeness states that any set of real numbers that is bounded above has a supremum. If you are not familiar with supremum, replace it with maximum and \nyou will be fine for all practical purposes.\n\nIntuitively, if the fit is perfect, $D_n = 0$. If the fit is terrible, $D_n$ \nis large.\n\n\n::: {.callout-note collapse=\"true\"}\n## The Infinity Norm\n\n\nA function $f$ on a domain $\\mathcal{D}$ is said to be **bounded** if there \nexists a real number $M > 0$ such that $|f(x)| \\leq M$ for all $x \\in \\mathcal{D}$.\n\nThe infinity norm (or sup norm) of a bounded function $f$ on a domain $\\mathcal{D}$ is defined as:\n\n$$\\|f\\|_\\infty = \\sup_{x \\in \\mathcal{D}} |f(x)|$$\n\nThe infinity norm naturally induces a metric between two functions $f$ and $g$:\n\n$$\\|f - g\\|_\\infty = \\sup_{x \\in \\mathcal{D}} |f(x) - g(x)|$$\n\n\nIt measures the **largest** absolute value the function attains over its entire \ndomain — the worst-case deviation. In our case, $\\hat{F}_n - F(\\cdot\\,;\\hat{\\theta},\\hat{\\gamma})$ \nis a function of time $t$, and $D_n = \\|\\hat{F}_n - F\\|_\\infty$ is its largest \nabsolute value over all $t \\geq 0$. The infinity norm is the natural norm on \nthe space of bounded functions $B(\\mathbb{R})$ and plays a central role in \nfunctional analysis and approximation theory.\n\nThe infinity norm is indeed a norm — it satisfies non-negativity, homogeneity, \nand the triangle inequality. Verifying these properties is a standard exercise \nin real analysis. The triangle inequality in particular:\n\n$$\\|f + g\\|_\\infty \\leq \\|f\\|_\\infty + \\|g\\|_\\infty$$\n\nfollows directly from $|f(x) + g(x)| \\leq |f(x)| + |g(x)|$ and taking the \nsupremum on both sides. In fact, the space of bounded functions on $\\mathbb{R}$ \nequipped with the infinity norm, denoted $B(\\mathbb{R})$, is not just a normed \nvector space but a **Banach space** — a complete normed vector space where every \nCauchy sequence converges. This completeness property is what makes the infinity \nnorm so powerful in analysis.\n\n:::\n\n#### The Hypothesis Test\n\n$$H_0: \\text{the data comes from } F(t; \\hat{\\theta}, \\hat{\\gamma})$$\n$$H_1: \\text{it doesn't}$$\n\nIf $D_n$ is large enough — larger than what you would expect by chance if \n$H_0$ is true — you reject the null.\n\n#### Distribution of $D_n$\n\nWithout going into the depths of hell, we simply state that under $H_0$ with \n**known parameters**, $\\sqrt{n} \\cdot D_n$ converges in distribution to the \nKolmogorov distribution $K$. The CDF of $K$ has the closed form:\n\n$$P(K \\leq x) = 1 - 2\\sum_{k=1}^{\\infty} (-1)^{k-1} e^{-2k^2x^2}$$\n\n#### A Critical Caveat\n\nThe standard K-S test assumes the parameters $\\theta$ and $\\gamma$ are \n**known in advance** — not estimated from the same data. In our case, we \nestimated $\\hat{\\theta}$ and $\\hat{\\gamma}$ from the machine fleet data using \nMLE, and then used those estimates to construct $F(t; \\hat{\\theta}, \\hat{\\gamma})$. \nThis makes $D_n$ artificially small — the fitted distribution has already been \npulled toward the data, so the two curves are closer than they would be with \ntruly known parameters. As a result, the standard K-S p-values are too \noptimistic and should not be taken at face value.\n\nFor our purposes, we use the K-S test as a descriptive tool — a way to \nquantify how close the fit is — rather than as a strict hypothesis test. \nThe Q-Q plot already told us the story visually. The K-S statistic puts a \nnumber on it. Let's see via code what that number looks like. \n\n::: {#ks-test-fleet .cell execution_count=7}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\nfrom lifelines import WeibullFitter\nfrom scipy import stats\n\ndf = pd.read_csv('../../data/machine_fleet.csv')\n\nwf = WeibullFitter()\nwf.fit(df['observed_time'], event_observed=df['event_observed'])\n\ngamma_hat = wf.rho_\ntheta_hat = wf.lambda_\n\n# Use only observed failures\nt_obs = df[df['event_observed'] == 1]['observed_time'].values\n\n# K-S test against fitted Weibull\n# scipy uses the standard Weibull parameterization\n# Weibull(c, scale) where c = gamma, scale = theta\nks_stat, p_value = stats.kstest(\n    t_obs,\n    'weibull_min',\n    args=(gamma_hat, 0, theta_hat)\n)\n\nprint(f\"K-S statistic  : {ks_stat:.4f}\")\nprint(f\"p-value        : {p_value:.4f}\")\nprint(f\"Sample size    : {len(t_obs)}\")\nprint()\nprint(\"Interpretation:\")\nif p_value < 0.05:\n    print(f\"  D_n = {ks_stat:.4f} — reject H0 at 5% significance.\")\n    print(\"  The fitted Weibull does not describe the data well.\")\nelse:\n    print(f\"  D_n = {ks_stat:.4f} — fail to reject H0 at 5% significance.\")\n    print(\"  The fitted Weibull is a reasonable description of the data.\")\nprint()\nprint(\"Note: p-value is anti-conservative since parameters were\")\nprint(\"estimated from the same data. Use as descriptive tool only.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nK-S statistic  : 0.0669\np-value        : 0.0007\nSample size    : 886\n\nInterpretation:\n  D_n = 0.0669 — reject H0 at 5% significance.\n  The fitted Weibull does not describe the data well.\n\nNote: p-value is anti-conservative since parameters were\nestimated from the same data. Use as descriptive tool only.\n```\n:::\n:::\n\n\n$D_n = 0.067$ and $p = 0.0007$ are both computed from the same test statistic, \nbut they answer different questions. $D_n$ measures the size of the deviation — \n6.7 percentage points at most, which is practically small. The p-value measures \nwhether a deviation this large is surprising given the sample size. With $n = 886$, \neven a small $D_n$ becomes highly significant — the test has enough power to \nconfidently declare the fit imperfect. This is a well known phenomenon in hypothesis testing — with large sample sizes, \neven small and practically irrelevant deviations from the null become statistically \nsignificant. The test is not broken. It is doing exactly what it is designed to do: \ndetect any deviation from $H_0$, no matter how small, given enough data. Whether \nthat deviation matters in practice is a separate question that the p-value cannot \nanswer.\n\nLet's spend a few minutes to analyze the output $D_n = 0.067$ and $p = 0.0007$ in practical terms. The small p-value \ntells us that the observed data is unlikely to have come from the fitted Weibull. Fine. The test statistic $D_n$ tells us that\nthe fitted CDF and the empirical CDF are never off by more than 6.7 percent at any time point. \n\nBecause for any time $t$:\n\n$$|\\hat{F}_n(t) - F(t;\\hat{\\theta}, \\hat{\\gamma})| \\leq D_n = 0.067$$\n\nNow suppose we use the fitted Weibull to make a decision: Schedule maintenance at time t* where the fitted CDF reaches 30% - i.e. act before 30% of the fleet has failed. Solving for t* gives,\n\n$$t^* = \\hat{\\theta}\\left[\\ln\\left(\\frac{1}{1-0.30}\\right)\\right]^{1/\\hat{\\gamma}} \\approx 56\\ \\text{hours}$$\n\nWe schedule maintenance at $t^* = 56$ hours. But by the K-S bound, the actual \nobserved failure fraction at $t = 56$ hours satisfies:\n\n$$|\\hat{F}_n(56) - 0.30| \\leq 0.067 \\implies \\hat{F}_n(56) \\in [0.233,\\ 0.367]$$\n\nOut of 1000 machines, between 233 and 367 have actually failed by the time we \ntrigger maintenance — a swing of $\\pm 67$ machines driven entirely by the \nmodel's imprecision. Let's assume:\n\n- Cost of an **unplanned failure**: ₹5,00,000 per machine\n- Cost of **preventive maintenance**: ₹50,000 per machine\n\nAt $t^* = 56$ hours, you service all 1000 machines regardless.\n\n**Best case** $\\left(\\hat{F}_n(56) = 0.233\\right)$: 233 machines had already \nfailed, 767 are still running.\n\n$$\\text{Total cost} = 233 \\times 5{,}00{,}000 + 767 \\times 50{,}000 = \\text{₹11,65,00,000} + \\text{₹3,83,50,000} = \\text{₹15,48,50,000}$$\n\n**Worst case** $\\left(\\hat{F}_n(56) = 0.367\\right)$: 367 machines had already \nfailed, 633 are still running.\n\n$$\\text{Total cost} = 367 \\times 5{,}00{,}000 + 633 \\times 50{,}000 = \\text{₹18,35,00,000} + \\text{₹3,16,50,000} = \\text{₹21,51,50,000}$$\n\nThe uncertainty from $D_n = 0.067$ alone translates into a cost swing of:\n\n$$\\text{₹21,51,50,000} - \\text{₹15,48,50,000} = \\text{₹6,03,00,000}$$\n\napproximately ₹6 crore. And crucially — we cannot identify *which* 67 machines \nare driving this uncertainty without knowing their individual characteristics. \nThat requires modeling the effect of covariates on failure time. This is \nprecisely what survival regression is built to do — and where we are headed. Let's visualize how the cost swing and the trigger time $t^*$ \nvary across all possible thresholds from 5% to 95%.\n\n::: {#cell-fig-cost-swing .cell execution_count=8}\n\n::: {.cell-output .cell-output-display}\n![Cost swing due to model uncertainty (D_n = 0.067) across maintenance thresholds](index_files/figure-html/fig-cost-swing-output-1.png){#fig-cost-swing width=1335 height=470}\n:::\n:::\n\n\nThe cost swing curve is nearly flat at ₹6 crore across all thresholds — \nthis is not a coincidence. Since $D_n$ is a uniform bound over all $t$, \nthe worst-case cost uncertainty is approximately:\n\n$$\\text{Cost swing} \\approx 2 D_n \\times n \\times (c_{\\text{failure}} - c_{\\text{maintenance}}) \n= 2 \\times 0.067 \\times 1000 \\times 4{,}50{,}000 = \\text{₹6.03 crore}$$ \nregardless of which threshold you choose. A better model — one that reduces \n$D_n$ — would shift this entire curve downward uniformly. The right panel \nshows the trigger time $t^*$ growing rapidly with threshold — waiting for \n90% of the fleet to fail before intervening means waiting nearly 180 hours.\n\n::: {.callout-note collapse=\"true\"}\n## Derivation of the Cost Swing Formula\n\nAt threshold $p^*$, you trigger maintenance at $t^*$ and service all $n$ \nmachines. Of those, $\\hat{F}_n(t^*) \\times n$ had already failed and each \ncosts $c_{\\text{failure}}$, while $(1 - \\hat{F}_n(t^*)) \\times n$ are still \nrunning and each costs $c_{\\text{maintenance}}$. The total cost is:\n\n$$\\text{Total cost} = \\hat{F}_n(t^*) \\cdot n \\cdot c_{\\text{failure}} + (1 - \\hat{F}_n(t^*)) \\cdot n \\cdot c_{\\text{maintenance}}$$\n\nBy the K-S bound, $\\hat{F}_n(t^*)$ lies in $[p^* - D_n,\\ p^* + D_n]$, so:\n\n$$p_{\\text{best}} = p^* - D_n, \\qquad p_{\\text{worst}} = p^* + D_n$$\n\nThe cost swing is:\n\n$$\\text{Cost swing} = \\text{Cost}_{\\text{worst}} - \\text{Cost}_{\\text{best}}$$\n\n$$= \\left[p_{\\text{worst}} \\cdot n \\cdot c_{\\text{failure}} + (1-p_{\\text{worst}}) \\cdot n \\cdot c_{\\text{maintenance}}\\right] - \\left[p_{\\text{best}} \\cdot n \\cdot c_{\\text{failure}} + (1-p_{\\text{best}}) \\cdot n \\cdot c_{\\text{maintenance}}\\right]$$\n\n$$= n(p_{\\text{worst}} - p_{\\text{best}})(c_{\\text{failure}} - c_{\\text{maintenance}})$$\n\n$$= n \\cdot 2D_n \\cdot (c_{\\text{failure}} - c_{\\text{maintenance}})$$\n\nThis is constant across all thresholds $p^*$ — the cost swing depends only \non $D_n$, $n$, and the cost difference, not on which threshold you choose.\n:::\n\n\n### What's Next? \n\nWe have covered a lot of ground in Part 3. We started with the likelihood function- a truly theoretical object- and derived the censored likelihood from first principles. We then fit a Weibull to our fleet machine and assessed the fit using two diagnostic tools- the Q-Q plot, which told the story visually and the K-S test, which put a number on it. \n\nAlong the way, we took a detour that went from the supremum norm of functional analysis $D_n = \\|\\hat{F}_n - F\\|_\\infty$ - all the way to a ₹6 crore cost swing for a fleet of 1000 machines. This is the range this series (and survival analysis) operates in: rigorous mathematics grounded in practical consequences. The K-S test is rooted in advanced concepts in stochastic processes and functional analysis but its practical meaning is completely accessible: how wrong can my model be, and what does that cost me?\n\nOne thing that Part-3 has made very clear: a single Weibull is not enough for a heterogeneous fleet of machines. The Q-Q plot showed deviations from the diagonal and the K-S test rejected the null hypothesis. The cost analysis showed ₹6 crore of uncertainty. We need a better model- one that accounts for the fact that different machines \nhave different failure characteristics.\n\nBut before we get to regression, we need a better estimator of the survival function itself - one that handles censored data properly, unlike the naive empirical CDF we used in the Q-Q plot. \n\nIn Part-4 we derive the most famous **Kaplan-Meier estimator** from first principles, prove **Greenwood's formula** for its variance, handle tied failure times rigorously, and apply both to our machine fleet. Most survival analysis blogs introduce this estimator in the very beginning- like an entry point to the field. We are arriving at it in Part-4, after three parts of solid mathematical groundwork: censoring, hazard functions, parametric distributions, MLE and the empirical CDF. This is not a detour. This is the foundation that the Kaplan-Meier estimatior deserves. The clock is still ticking. See you in the next post. \n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}