<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Madhav Prashanth Ramachandran">
<meta name="dcterms.date" content="2026-04-19">

<title>Part 3: Fitting Survival Distributions to Data – Madhav’s Blog</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-a0f9fd0d421825b736dc1bbcbcba2219.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>



<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Madhav’s Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://bsky.app/"> <i class="bi bi-bluesky" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Part 3: Fitting Survival Distributions to Data</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">survival analysis</div>
                <div class="quarto-category">statistics</div>
                <div class="quarto-category">python</div>
                <div class="quarto-category">MLE</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Madhav Prashanth Ramachandran </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">April 19, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="recap-of-part-2-and-whats-coming-in-part-3" class="level2">
<h2 class="anchored" data-anchor-id="recap-of-part-2-and-whats-coming-in-part-3">Recap of Part 2 and What’s Coming in Part 3</h2>
<p>In <strong>Part 2</strong>, we built a vocabulary of survival distributions — the Exponential for constant hazard, the Rayleigh for linearly increasing hazard, and the Weibull as the unifying family that contains both as special cases. Along the way we took a detour through the connection between the Rayleigh, Normal, and Exponential distributions, and ended with the bathtub curve — the most common failure pattern in real engineered systems.</p>
<p>But a distribution is not a model until it is fit to data. In <strong>Part 3</strong>, we ask: given a dataset of failure times — some exact, some censored — how do we estimate the parameters of these distributions? We will derive the likelihood function under censoring from first principles, apply maximum likelihood estimation, and assess the quality of our fits using diagnostic tools. Python code throughout using <code>lifelines</code>.</p>
<section id="maximum-likelihood-estimation" class="level3">
<h3 class="anchored" data-anchor-id="maximum-likelihood-estimation">Maximum Likelihood Estimation</h3>
<p>We will review the maximum likelihood estimation (MLE) framework with a simple example. We will then extend this framework to handle censored data, which is what makes survival analysis different from classical statistical inference. We will derive the likelihood function for censored data, and then apply MLE to estimate the parameters of the distributions we have discussed. We will simulate some synthetic data to demonstrate the MLE process in practice. If you are new to MLE and feel lost, you can consult any standard statistics textbook or an online resource for a more detailed introduction. The key idea is that MLE provides a systematic way to estimate the parameters of a statistical model by finding the parameter values that maximize the likelihood of observing the given data.</p>
<section id="the-likelihood-function" class="level4">
<h4 class="anchored" data-anchor-id="the-likelihood-function">The Likelihood Function</h4>
<p>This is the heart of the matter. Likelihoods often are confused with probabilities – they look similar, their forms are similar but they are conceptually different. In probability, we ask: given a model with known parameters, what is the chance of observing the data? In likelihood, we ask: given the observed data, what is the chance that the data came from a model with certain parameters? To give a concrete example, suppose we observe a failure time of 5 hours. Let’s suppose we have a model that says the failure time follows an exponential distribution with a mean of 10 hours. Probability asks: What is the probability of observing a failure between 4 and 6 hours given this model? Likelihood asks: Across all possible values of the mean (or rate) parameter, for which value does the observed time of 5 hours seems most plausible?</p>
<p>Here is the setup. We have a sequence of observed failure times <span class="math inline">\(t_1, t_2, \ldots, t_n\)</span> that we assume are independent and identically distributed (i.i.d.) samples from some distribution with a parameter <span class="math inline">\(\theta\)</span>. The likelihood function is defined as the joint probability of observing this data given the parameter <span class="math inline">\(\theta\)</span>: In the simplest setup, we will assume that all observations are exact failure times (no censoring). In that case, the likelihood function is:</p>
<p><span class="math display">\[L(\theta) = P(t_1, t_2, \ldots, t_n ; \theta)\]</span></p>
<p>Note that this is a function of <span class="math inline">\(\theta\)</span> - we are treating the data as fixed and asking how likely different values of <span class="math inline">\(\theta\)</span> are to have generated this data. Since most of our work will involve continuous distributions, we will often work with the probability density function (pdf) instead of the probability mass function (pmf). In that case, the likelihood becomes:</p>
<p><span class="math display">\[L(\theta) = f(t_1 ; \theta) \cdot f(t_2 ; \theta) \cdot \ldots \cdot f(t_n ; \theta) = \prod_{i=1}^n f(t_i ; \theta)\]</span></p>
<p>Note that some authors use the conditional probability notation <span class="math inline">\(P(t_i | \theta)\)</span> instead of the joint probability notation <span class="math inline">\(P(t_1, t_2, \ldots, t_n ; \theta)\)</span>, but the meaning is the same. The likelihood function captures how well the model with parameter <span class="math inline">\(\theta\)</span> explains the observed data. The MLE process will involve finding the value of <span class="math inline">\(\theta\)</span> that maximizes this likelihood function. We will use the semicolons in the notation to emphasize that we are treating the data as fixed and the parameter as an unknown constant. If the parameter is itself a random variable with a prior distribution, then we are in the realm of Bayesian inference, which is a different framework. In MLE, we do not assign a prior distribution to the parameter; we simply find the value that maximizes the likelihood of the observed data.</p>
</section>
<section id="the-maximum-likelihood-estimation-process" class="level4">
<h4 class="anchored" data-anchor-id="the-maximum-likelihood-estimation-process">The Maximum Likelihood Estimation Process</h4>
<p>The MLE process involves finding the value of <span class="math inline">\(\theta\)</span> that maximizes the likelihood function <span class="math inline">\(L(\theta)\)</span>. In practice, it is often easier to work with the log-likelihood function, which is the natural logarithm of the likelihood:</p>
<p><span class="math display">\[\ell(\theta) = \log L(\theta) = \sum_{i=1}^n \log f(t_i ; \theta)\]</span></p>
<p>The MLE estimate <span class="math inline">\(\hat{\theta}_{\text{MLE}}\)</span> is the value of <span class="math inline">\(\theta\)</span> that maximizes <span class="math inline">\(\ell(\theta)\)</span>:</p>
<p><span class="math display">\[\hat{\theta}_{\text{MLE}} = \arg\max_{\theta} \ell(\theta)\]</span></p>
<p>If the likelihood function is well-behaved (e.g., it is differentiable), we can find the MLE estimate by taking the derivative of the log-likelihood with respect to <span class="math inline">\(\theta\)</span>, setting it equal to zero, and solving for <span class="math inline">\(\theta\)</span>. This gives us the critical points of the log-likelihood function, which we can then evaluate to find the maximum. To show that the critical point we find is indeed a maximum, we can check the second derivative or use other methods if necessary. Let’s see how this works in practice with a simple example.</p>
<p>Suppose we have a dataset of failure times that we believe follows an exponential distribution. The exponential distribution has a single parameter <span class="math inline">\(\lambda\)</span> (the rate), and its pdf is given by:</p>
<p><span class="math display">\[f(t ; \lambda) = \lambda e^{-\lambda t}\]</span></p>
<p>Given a dataset of failure times <span class="math inline">\(t_1, t_2, \ldots, t_n\)</span>, the likelihood function for the exponential distribution is:</p>
<p><span class="math display">\[L(\lambda) = \prod_{i=1}^n \lambda e^{-\lambda t_i} = \lambda^n e^{-\lambda \sum_{i=1}^n t_i}\]</span></p>
<p>The log-likelihood function is:</p>
<p><span class="math display">\[\ell(\lambda) = n \log \lambda - \lambda \sum_{i=1}^n t_i\]</span></p>
<p>To find the MLE estimate <span class="math inline">\(\hat{\lambda}\)</span>, we take the derivative of <span class="math inline">\(\ell(\lambda)\)</span> with respect to <span class="math inline">\(\lambda\)</span>, set it equal to zero, and solve for <span class="math inline">\(\lambda\)</span>:</p>
<p><span class="math display">\[\frac{d\ell}{d\lambda} = \frac{n}{\lambda} - \sum_{i=1}^n t_i = 0\]</span></p>
<p>Solving for <span class="math inline">\(\lambda\)</span> gives us: <span class="math display">\[\hat{\lambda}_{\text{MLE}} = \frac{n}{\sum_{i=1}^n t_i}\]</span></p>
<p>This is the MLE estimate for the rate parameter of the exponential distribution based on our observed failure times. Notice that this estimate is simply the reciprocal of the sample mean of the failure times, which makes intuitive sense given the properties of the exponential distribution. We can verify that this critical point is indeed a maximum by checking the second derivative of the log-likelihood function evaluated at <span class="math inline">\(\hat{\lambda}_{\text{MLE}}\)</span>:</p>
<p><span class="math display">\[\frac{d^2\ell}{d\lambda^2} = -\frac{n}{\lambda^2}\]</span></p>
<p>which is negative for all <span class="math inline">\(\lambda &gt; 0\)</span>. Therefore, we have a maximum at <span class="math inline">\(\hat{\lambda}_{\text{MLE}}\)</span>. In fact, the (only) critical point we find is a global maximum.</p>
<p>For a vector of parameters <span class="math inline">\(\boldsymbol{\theta}\)</span> with components <span class="math inline">\(\theta_1, \theta_2, \ldots, \theta_p\)</span>, the MLE process is similar but we take the gradient of the log-likelihood with respect to the vector of parameters and set it equal to the zero vector to find the critical points. We can then use the Hessian matrix to check whether we have a maximum, minimum, or saddle point. For instance, the Weibull distribution has two parameters, the shape <span class="math inline">\(\gamma\)</span> and the scale <span class="math inline">\(\theta\)</span>. The MLE process would involve taking the gradient of the log-likelihood with respect to both <span class="math inline">\(\gamma\)</span> and <span class="math inline">\(\theta\)</span>, setting it equal to zero, and solving for both parameters simultaneously. Let’s derive the MLE equations for the Weibull distribution. Suppose you have a dataset of failure times <span class="math inline">\(t_1, t_2, \ldots, t_n\)</span> that you believe follows a Weibull distribution with shape parameter <span class="math inline">\(\gamma\)</span> and scale parameter <span class="math inline">\(\theta\)</span>. The pdf of the Weibull distribution is given by:</p>
<p><span class="math display">\[f(t ; \gamma, \theta) = \frac{\gamma}{\theta} \left( \frac{t}{\theta} \right)^{\gamma - 1} e^{-(t/\theta)^\gamma}\]</span></p>
<p>The likelihood function for the Weibull distribution is:</p>
<p><span class="math display">\[L(\gamma, \theta) = \prod_{i=1}^n \frac{\gamma}{\theta} \left( \frac{t_i}{\theta} \right)^{\gamma - 1} e^{-(t_i/\theta)^\gamma}\]</span></p>
<p>The log-likelihood function is:</p>
<p><span class="math display">\[\ell(\gamma, \theta) = n\log\gamma - n\gamma\log\theta + (\gamma - 1)\sum_{i=1}^n \log t_i - \sum_{i=1}^n \left(\frac{t_i}{\theta}\right)^\gamma\]</span></p>
<p>To find the MLE estimates <span class="math inline">\(\hat{\gamma}\)</span> and <span class="math inline">\(\hat{\theta}\)</span>, we take the gradient of <span class="math inline">\(\ell(\gamma, \theta)\)</span> with respect to both parameters, set it equal to zero, and solve for <span class="math inline">\(\gamma\)</span> and <span class="math inline">\(\theta\)</span>. This will give us a system of equations that we can solve numerically to find the MLE estimates. The resulting equations are nonlinear and do not have a closed-form solution, which is why we need numerical optimization methods to find the MLE estimates for the Weibull distribution. We will see how to do this in practice using <code>lifelines</code> in the simulation below.</p>
<div id="cell-fig-weibull-mle" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> lifelines <span class="im">import</span> WeibullFitter</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate synthetic Weibull data</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>true_gamma <span class="op">=</span> <span class="fl">2.0</span>   <span class="co"># shape</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>true_theta <span class="op">=</span> <span class="fl">100.0</span>  <span class="co"># scale</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">200</span>  <span class="co"># number of samples</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Weibull random samples using inverse CDF</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>u <span class="op">=</span> np.random.uniform(<span class="dv">0</span>, <span class="dv">1</span>, n)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>t <span class="op">=</span> true_theta <span class="op">*</span> (<span class="op">-</span>np.log(<span class="dv">1</span> <span class="op">-</span> u))<span class="op">**</span>(<span class="dv">1</span><span class="op">/</span>true_gamma)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># All observed (no censoring yet)</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>event_observed <span class="op">=</span> np.ones(n)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>wf <span class="op">=</span> WeibullFitter()</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>wf.fit(t, event_observed<span class="op">=</span>event_observed)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>wf.print_summary()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="fig-weibull-mle" class="cell-output cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-weibull-mle-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">model</th>
<td>lifelines.WeibullFitter</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">number of observations</th>
<td>200</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">number of events observed</th>
<td>200</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">log-likelihood</th>
<td>-1035.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">hypothesis</th>
<td>lambda_ != 1, rho_ != 1</td>
</tr>
</tbody>
</table>

</div>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="min-width: 12px"></th>
<th data-quarto-table-cell-role="th" style="min-width: 12px">coef</th>
<th data-quarto-table-cell-role="th" style="min-width: 12px">se(coef)</th>
<th data-quarto-table-cell-role="th" style="min-width: 12px">coef lower 95%</th>
<th data-quarto-table-cell-role="th" style="min-width: 12px">coef upper 95%</th>
<th data-quarto-table-cell-role="th" style="min-width: 12px">cmp to</th>
<th data-quarto-table-cell-role="th" style="min-width: 12px">z</th>
<th data-quarto-table-cell-role="th" style="min-width: 12px">p</th>
<th data-quarto-table-cell-role="th" style="min-width: 12px">-log2(p)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">lambda_</th>
<td>97.18</td>
<td>3.63</td>
<td>90.06</td>
<td>104.29</td>
<td>1.00</td>
<td>26.50</td>
<td>&lt;0.005</td>
<td>511.45</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">rho_</th>
<td>1.99</td>
<td>0.11</td>
<td>1.78</td>
<td>2.21</td>
<td>1.00</td>
<td>8.93</td>
<td>&lt;0.005</td>
<td>60.96</td>
</tr>
</tbody>
</table>
<br><div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">AIC</th>
<td>2074.19</td>
</tr>
</tbody>
</table>

</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-weibull-mle-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1
</figcaption>
</figure>
</div>
</div>
<p><code>lifelines</code> uses <code>lambda_</code> for the scale parameter <span class="math inline">\(\theta\)</span> and <code>rho_</code> for the shape parameter <span class="math inline">\(\gamma\)</span> — different notation, same parameters. With <span class="math inline">\(n = 200\)</span> observations, the estimated parameters are already close to the true values:</p>
<p><span class="math display">\[\hat{\gamma} = 1.99 \approx 2.0 = \gamma_{\text{true}}, \qquad \hat{\theta} = 97.18 \approx 100.0 = \theta_{\text{true}}\]</span></p>
<p>MLE recovers the true parameters with high accuracy even at modest sample sizes.</p>
<div id="cell-fig-weibull-fit" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div id="fig-weibull-fit" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-weibull-fit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-weibull-fit-output-1.png" width="853" height="470" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-weibull-fit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Fitted Weibull survival curve vs empirical survival curve
</figcaption>
</figure>
</div>
</div>
</div>
<p>The fitted Weibull survival curve (gold) closely tracks the empirical survival function (blue) across the entire time range. The empirical survival function is simply the fraction of systems still surviving at each time point — no distributional assumptions, just the raw data speaking for itself. The fact that the fitted curve hugs it so tightly tells us two things: MLE found good parameter estimates, and the Weibull is a reasonable model for this data. We will make this “goodness of fit” assessment more rigorous later using diagnostic tools.</p>
<p>But there is a catch — this was the easy case. All 200 observations were exact failure times. In practice, not all machines will have failed by the end of the study — some will still be running when the study ends. How do we modify the likelihood function to account for censoring? This is the key question that makes survival analysis different from classical statistical inference. We derive the censored likelihood function from first principles next.</p>
</section>
</section>
<section id="mle-with-censored-data" class="level3">
<h3 class="anchored" data-anchor-id="mle-with-censored-data">MLE with Censored Data</h3>
<p>Remember that in survival analysis, we often have censored data — we know that a system survived up to a certain time, but we don’t know the exact failure time. This is called right-censoring. We need to modify our likelihood function to account for this type of data. Recall from Part 1 of the series that we observe pairs of the form <span class="math inline">\((Y_i, \delta_i)\)</span> where <span class="math inline">\(Y_i = \min(T_i, C_i)\)</span> is the observed time (either failure time or censoring time) and <span class="math inline">\(\delta_i\)</span> is an indicator variable that is 1 if the event (failure) was observed and 0 if it was censored. If <span class="math inline">\(\delta_i = 1\)</span>, we know that the failure time <span class="math inline">\(T_i\)</span> was observed and is equal to <span class="math inline">\(Y_i\)</span>. If <span class="math inline">\(\delta_i = 0\)</span>, we know that the system survived up to time <span class="math inline">\(Y_i\)</span>, but we don’t know the exact failure time.</p>
<p>A brief notational remark before we proceed further. <span class="math inline">\(T_i\)</span> and <span class="math inline">\(C_i\)</span> are random variables representing the (unknown) failure time and censoring time of the <span class="math inline">\(i\)</span>-th unit. Their realizations — the actual observed values — are denoted <span class="math inline">\(t_i\)</span> and <span class="math inline">\(c_i\)</span> in lowercase. <span class="math inline">\(Y_i = \min(T_i, C_i)\)</span> is also a random variable, and its realization is <span class="math inline">\(y_i = \min(t_i, c_i)\)</span>. We use uppercase for random variables and lowercase for their observed values throughout.</p>
<p>How does this affect the likelihood function? For an observed failure time (when <span class="math inline">\(\delta_i = 1\)</span>), the contribution to the likelihood is simply the pdf evaluated at <span class="math inline">\(Y_i\)</span>: <span class="math inline">\(f(y_i ; \theta)\)</span>. This is equal to the pdf evaluated at the failure time <span class="math inline">\(t_i\)</span>.</p>
<p>For a censored observation (when <span class="math inline">\(\delta_j = 0\)</span>), the observation tells us that the failure time <span class="math inline">\(T_j\)</span> is greater than <span class="math inline">\(Y_j\)</span>. The contribution to the likelihood is the probability that the system survived past <span class="math inline">\(Y_j\)</span>, which is given by the survival function: <span class="math inline">\(S(Y_j ; \theta) = P(T_j &gt; Y_j)\)</span>.</p>
<p>The full likelihood function for a dataset with both exact failure times and censored observations is the product of the contributions from all observations:</p>
<p><span class="math display">\[L(\theta) = \prod_{i=1}^n [f(y_i ; \theta)]^{\delta_i} [S(y_i ; \theta)]^{1 - \delta_i}\]</span></p>
<p>You might be wondering why we have the exponents <span class="math inline">\(\delta_i\)</span> and <span class="math inline">\(1 - \delta_i\)</span> in the likelihood function. This is a common way to write the likelihood function in survival analysis to compactly represent both types of observations. When <span class="math inline">\(\delta_i = 1\)</span>, the term <span class="math inline">\([f(y_i ; \theta)]^{\delta_i}\)</span> becomes <span class="math inline">\(f(y_i ; \theta)\)</span> and the term <span class="math inline">\([S(y_i ; \theta)]^{1 - \delta_i}\)</span> becomes 1, so the contribution to the likelihood is just <span class="math inline">\(f(y_i ; \theta)\)</span>. When <span class="math inline">\(\delta_j = 0\)</span>, the term <span class="math inline">\([f(y_j ; \theta)]^{\delta_j}\)</span> becomes 1 and the term <span class="math inline">\([S(y_j ; \theta)]^{1 - \delta_j}\)</span> becomes <span class="math inline">\(S(y_j ; \theta)\)</span>, so the contribution to the likelihood is just <span class="math inline">\(S(y_j ; \theta)\)</span>. This way of writing the likelihood function allows us to handle both types of observations in a unified framework. This is very similar to writing the likelihood function (or loss function) in logistic regression, where we have a binary outcome and we use the observed labels to determine which term contributes to the likelihood for each observation.</p>
<p>Finally, a point worth observing is that the likelihood function for censored data is not a simple product of pdfs, but rather a product of a mixture of pdfs and survival functions. How can you combine the PDF (which is a density) and the survival function (which is a probability) in the same likelihood function? The answer lies in the fact that we are not comparing incompatible objects. For a censored observation, <span class="math inline">\(S(y_j;\theta) = P(T_j &gt; y_j)\)</span> is a genuine probability. For an exact failure, <span class="math inline">\(f(y_i;\theta)\)</span> is a density — but both contribute to the same likelihood because we are asking the same question for each observation: what parameter value <span class="math inline">\(\theta\)</span> makes this observation most plausible? The likelihood function combines these two types of contributions in a unified framework that allows MLE to work even in the presence of censoring.</p>
<p>If you want to be very abstract and not make a big deal about the fact that we are mixing densities and probabilities, you can just think of the likelihood function as a product of two functions and you are trying to find the parameter values that maximize this product. The abstract view strips away the details and allows you to focus on the optimization problem. However, it has a disadvantage that it takes away the intuition about why we are using the pdf for exact failures and the survival function for censored observations. The more concrete view emphasizes the different contributions to the likelihood from different types of observations, which can help build intuition about how MLE works in the presence of censoring. Both views are valid and can be useful in different contexts.</p>
<p>Let’s spend some more time on understanding true failure <span class="math inline">\(\delta = 1\)</span> vs censoring <span class="math inline">\(\delta = 0\)</span> and how they contribute to the likelihood function a little more intuitively.</p>
<p>Case 1: <strong><span class="math inline">\(\delta_i = 1\)</span> (exact failure observed)</strong>.</p>
<p>In this case, we know that the <strong>observed</strong> failure time <span class="math inline">\(t_i\)</span> (a realization of <span class="math inline">\(T_i\)</span>) is less than or equal to the censoring time <span class="math inline">\(C_i\)</span>. Consider the event that the failure time <span class="math inline">\(T_i \leq C_i\)</span> and the failure time is in a small interval around <span class="math inline">\(t_i\)</span>. If the censoring time <span class="math inline">\(C_i\)</span> and the failure time <span class="math inline">\(T_i\)</span> are independent, then the joint probability of observing a failure at time <span class="math inline">\(t_i\)</span> and it being uncensored can be expressed as:</p>
<p><span class="math display">\[P(T_i \in [t_i, t_i + \Delta t], T_i \leq C_i) = P(T_i \in [t_i, t_i + \Delta t]) \cdot P(C_i \geq t_i)\]</span> The first term <span class="math inline">\(P(T_i \in [t_i, t_i + \Delta t])\)</span> is approximately equal to the pdf evaluated at <span class="math inline">\(t_i\)</span>: <span class="math inline">\(f(t_i ; \theta) \Delta t\)</span>. The second term <span class="math inline">\(P(C_i \geq t_i)\)</span> is the probability that the censoring time is greater than or equal to <span class="math inline">\(t_i\)</span>, which is given by the survival function of the censoring distribution evaluated at <span class="math inline">\(t_i\)</span>: <span class="math inline">\(S_C(t_i)\)</span>. Therefore, the contribution to the likelihood from an exact failure observation can be expressed as:</p>
<p><span class="math display">\[P(T_i \in [t_i, t_i + \Delta t], T_i \leq C_i) = f(t_i ; \theta) \, \Delta t \cdot S_C(t_i)\]</span></p>
<p>Since we are maximizing the likelihood with respect to <span class="math inline">\(\theta\)</span>, the term <span class="math inline">\(S_C(t_i)\)</span> does not depend on <span class="math inline">\(\theta\)</span> and can be treated as a constant. Therefore, the contribution to the likelihood from an exact failure observation is effectively proportional to the pdf evaluated at <span class="math inline">\(t_i\)</span>: <span class="math inline">\(f(t_i ; \theta)\)</span>. This is why we use the pdf for exact failure observations in the likelihood function. Note that the term <span class="math inline">\(S_C(t_i)\)</span> is the survival function of the censoring distribution, which represents the probability that the censoring time is greater than or equal to <span class="math inline">\(t_i\)</span> and therefore has nothing to do with the failure parameters <span class="math inline">\(\theta\)</span> that we are trying to estimate.</p>
<p>Case 2: <strong><span class="math inline">\(\delta_j = 0\)</span> (censored observation)</strong>.</p>
<p>In this case, we know that the system survived up to time <span class="math inline">\(y_j\)</span>, but we don’t know the exact failure time. The contribution to the likelihood from a censored observation is the probability that the failure time <span class="math inline">\(T_j\)</span> is greater than <span class="math inline">\(y_j\)</span>: <span class="math inline">\(P(T_j &gt; y_j) = S(y_j ; \theta)\)</span>. We know with certainty that the system survived up to time <span class="math inline">\(y_j\)</span>, so the likelihood contribution is the probability of surviving past that time, which is given by the survival function. Consider the event that the failure time <span class="math inline">\(T_j\)</span> is greater than <span class="math inline">\(y_j\)</span> and the censoring time <span class="math inline">\(C_j\)</span> is in a small interval around <span class="math inline">\(y_j\)</span>. If the censoring time <span class="math inline">\(C_j\)</span> and the failure time <span class="math inline">\(T_j\)</span> are independent, then the joint probability of observing a censored observation at time <span class="math inline">\(y_j\)</span> can be expressed as:</p>
<p><span class="math display">\[P(T_j &gt; y_j, C_j \in [y_j, y_j + \Delta t]) = P(T_j &gt; y_j) \cdot P(C_j \in [y_j, y_j + \Delta t])\]</span></p>
<p>The first term <span class="math inline">\(P(T_j &gt; y_j)\)</span> is the probability that the failure time is greater than <span class="math inline">\(y_j\)</span>, which is given by the survival function evaluated at <span class="math inline">\(y_j\)</span>: <span class="math inline">\(S(y_j ; \theta)\)</span>. The second term <span class="math inline">\(P(C_j \in [y_j, y_j + \Delta t])\)</span> is approximately equal to the pdf of the censoring distribution evaluated at <span class="math inline">\(Y_j\)</span>: <span class="math inline">\(f_C(y_j) \Delta t\)</span>. Therefore, the contribution to the likelihood from a censored observation can be expressed as:</p>
<p><span class="math display">\[P(T_j &gt; y_j, C_j \in [y_j, y_j + \Delta t]) = S(y_j ; \theta) \cdot f_C(y_j) \Delta t\]</span></p>
<p>Since we are maximizing the likelihood with respect to <span class="math inline">\(\theta\)</span>, the term <span class="math inline">\(f_C(Y_j) \Delta t\)</span> does not depend on <span class="math inline">\(\theta\)</span> and can be treated as a constant. Therefore, the contribution to the likelihood from a censored observation is effectively proportional to the survival function evaluated at <span class="math inline">\(Y_j\)</span>: <span class="math inline">\(S(y_j ; \theta)\)</span>. This is why we use the survival function for censored observations in the likelihood function. Note that the term <span class="math inline">\(f_C(y_j) \Delta t\)</span> is the pdf of the censoring distribution, which represents the probability of observing a censoring event at time <span class="math inline">\(Y_j\)</span> and therefore has nothing to do with the failure parameters <span class="math inline">\(\theta\)</span> that we are trying to estimate.</p>
<p>Combining both cases and all the observations, the full censored likelihood is:</p>
<p><span class="math display">\[L(\theta) = \prod_{i=1}^n [f(y_i ; \theta)]^{\delta_i} [S(y_i ; \theta)]^{1 - \delta_i}\]</span></p>
<p>where the <span class="math inline">\(\Delta t\)</span> and censoring distribution terms have been absorbed into a proportionality constant that does not affect the location of the maximum.</p>
<p>The assumption of independence between the failure time and censoring time is crucial for this derivation. This is known as the <strong>non-informative censoring assumption</strong>, which tells us that knowing when a subject was censored does not give us any information about their failure time. This assumption is violated in some real world scenarios, such as when a machine operator decides to stop a machine that is showing signs of imminent failure, or when a patient drops out of a clinical trial due to worsening health. In such cases, the censoring is informative and the standard MLE approach may yield biased estimates. There are methods to handle informative censoring, such as joint modeling of the failure and censoring processes, but these are beyond the scope of this post.</p>
<section id="the-log-likelihood-function-with-censoring" class="level4">
<h4 class="anchored" data-anchor-id="the-log-likelihood-function-with-censoring">The Log-Likelihood Function with Censoring</h4>
<p>The full censored likelihood function is:</p>
<p><span class="math display">\[L(\theta) = \prod_{i=1}^n [f(y_i ; \theta)]^{\delta_i} [S(y_i ; \theta)]^{1-\delta_i}\]</span></p>
<p>Taking the natural logarithm of the likelihood function gives us the log-likelihood function:</p>
<p><span class="math display">\[\ell(\theta) = \sum_{i=1}^n \left[ \delta_i \log f(y_i ; \theta) + (1 - \delta_i) \log S(y_i ; \theta) \right]\]</span></p>
<p>Based on our previous study of the relationship between the pdf and the survival function, we can express the log-likelihood function in terms of the hazard function <span class="math inline">\(\lambda(t ; \theta)\)</span>. Recall that the pdf can be expressed as <span class="math inline">\(f(t ; \theta) = \lambda(t ; \theta) S(t ; \theta)\)</span>, so we can rewrite the log-likelihood function as:</p>
<p><span class="math display">\[\ell(\theta) = \sum_{i=1}^n \left[ \delta_i \log \lambda(y_i ; \theta) + \log S(y_i ; \theta) \right]\]</span></p>
<p>Notice that <span class="math inline">\(\log S(y_i;\theta)\)</span> appears for <strong>every</strong> observation regardless of whether it failed or was censored — survival information contributes to the likelihood for all units. The hazard term <span class="math inline">\(\delta_i \log \lambda(y_i;\theta)\)</span> only contributes for observed failures. This is the elegance of the censored likelihood. Finally, we can express the log-likelihood function in terms of the cumulative hazard function <span class="math inline">\(\Lambda(t ; \theta)\)</span> using the relationship <span class="math inline">\(S(t ; \theta) = e^{-\Lambda(t ; \theta)}\)</span>:</p>
<p><span class="math display">\[\ell(\theta) = \sum_{i=1}^n \left[ \delta_i \log \lambda(y_i ; \theta) - \Lambda(y_i ; \theta) \right]\]</span></p>
<p>Now we use our calculus machinery to find the MLE estimates. Taking the derivative of the log-likelihood function with respect to <span class="math inline">\(\theta\)</span> and setting it equal to zero gives us the MLE equations that we can solve to find the parameter estimates. The specific forms of these equations will depend on the distribution we are fitting. And sometimes, these equations will be so nonlinear and complex that we won’t be able to solve them analytically. We will see how to handle this in practice using numerical optimization methods in <code>lifelines</code> when we fit the Weibull distribution with censored data in the next section.</p>
<p>But first, let’s calculate the analytical MLE estimates for the exponential distribution with censored data to see how the presence of censoring modifies the MLE equations. The exponential distribution has a single parameter <span class="math inline">\(\lambda\)</span> (the rate), and its pdf and survival function are given by:</p>
<p><span class="math display">\[f(t ; \lambda) = \lambda e^{-\lambda t}\]</span> <span class="math display">\[S(t ; \lambda) = e^{-\lambda t}\]</span></p>
<p>The log-likelihood function for the exponential distribution with censored data is:</p>
<p><span class="math display">\[\ell(\lambda) = \sum_{i=1}^n \left[ \delta_i \log (\lambda e^{-\lambda y_i}) + (1 - \delta_i) \log (e^{-\lambda y_i}) \right]\]</span></p>
<p>This simplifies to:</p>
<p><span class="math display">\[\ell(\lambda) = \sum_{i=1}^n \left[ \delta_i \log \lambda - \lambda y_i \right]\]</span></p>
<p>Taking the derivative of the log-likelihood function with respect to <span class="math inline">\(\lambda\)</span> and setting it equal to zero gives us:</p>
<p><span class="math display">\[\frac{d\ell}{d\lambda} = \sum_{i=1}^n \left[ \frac{\delta_i}{\lambda} - y_i \right] = 0\]</span></p>
<p>Solving for <span class="math inline">\(\lambda\)</span> gives us the MLE estimate for the exponential distribution with censored data:</p>
<p><span class="math display">\[\hat{\lambda}_{\text{MLE}} = \frac{\sum_{i=1}^n \delta_i}{\sum_{i=1}^n y_i}\]</span></p>
<p>The quantity <span class="math inline">\(\sum_{i=1}^n y_i\)</span> is known as the <strong>total time at risk</strong>, which is the sum of the observed times for all units, regardless of whether they failed or were censored. Each unit contributes to the total time at risk based on its observed duration. The quantity <span class="math inline">\(\sum_{i=1}^n \delta_i\)</span> is the total number of observed failures.</p>
<p>Isn’t this marvelous? The MLE estimate for the rate parameter <span class="math inline">\(\lambda\)</span> in the presence of censoring is simply the total number of observed failures (the sum of <span class="math inline">\(\delta_i\)</span>) divided by the total time at risk (the sum of <span class="math inline">\(y_i\)</span>). If the data were fully observed with no censoring, then <span class="math inline">\(\sum_{i=1}^n \delta_i = n\)</span> and we would recover the MLE estimate for the exponential distribution without censoring: <span class="math inline">\(\hat{\lambda}_{\text{MLE}} = \frac{n}{\sum_{i=1}^n y_i}\)</span> (I have used <span class="math inline">\(y_i\)</span> instead of <span class="math inline">\(t_i\)</span> for consistency with the current topic). The presence of censoring effectively reduces the number of observed failures and increases the total time at risk, which leads to a different MLE estimate that accounts for the incomplete information in the data. This is the power of the censored likelihood function — it allows us to make valid inferences about the parameters of the failure distribution even when we have incomplete data due to censoring. It is left an exercise for the reader to verify that the MLE estimate for the exponential distribution with censored data is indeed a maximum by checking the second derivative of the log-likelihood function evaluated at <span class="math inline">\(\hat{\lambda}_{\text{MLE}}\)</span>.</p>
</section>
<section id="mle-with-censoring-a-synthetic-data-example" class="level4">
<h4 class="anchored" data-anchor-id="mle-with-censoring-a-synthetic-data-example">MLE with Censoring: A synthetic data example</h4>
<p>Rather than working with abstract numbers and symbols, let’s build a dataset that will accompany us for the rest of the series- a synthetic fleet of 1000 machines, each with its own age, operating conditions, and failure history.</p>
<div id="dataset-generation" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Continuous covariates ---</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>machine_age        <span class="op">=</span> np.random.uniform(<span class="dv">0</span>, <span class="dv">15</span>, n)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>usage_intensity    <span class="op">=</span> np.random.uniform(<span class="fl">0.5</span>, <span class="fl">2.0</span>, n)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>operating_temp     <span class="op">=</span> np.random.uniform(<span class="dv">60</span>, <span class="dv">120</span>, n)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>load_factor        <span class="op">=</span> np.random.uniform(<span class="fl">0.3</span>, <span class="fl">1.0</span>, n)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>rpm                <span class="op">=</span> np.random.uniform(<span class="dv">500</span>, <span class="dv">3000</span>, n)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>vibration_level    <span class="op">=</span> np.random.uniform(<span class="fl">0.5</span>, <span class="dv">10</span>, n)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>oil_quality        <span class="op">=</span> np.random.uniform(<span class="dv">0</span>, <span class="dv">1</span>, n)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>maintenance_count  <span class="op">=</span> np.random.randint(<span class="dv">0</span>, <span class="dv">21</span>, n).astype(<span class="bu">float</span>)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Categorical covariates ---</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>environment  <span class="op">=</span> np.random.choice([<span class="st">'indoor'</span>, <span class="st">'outdoor'</span>, <span class="st">'harsh'</span>], n, p<span class="op">=</span>[<span class="fl">0.4</span>, <span class="fl">0.4</span>, <span class="fl">0.2</span>])</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>manufacturer <span class="op">=</span> np.random.choice([<span class="st">'A'</span>, <span class="st">'B'</span>, <span class="st">'C'</span>], n, p<span class="op">=</span>[<span class="fl">0.4</span>, <span class="fl">0.35</span>, <span class="fl">0.25</span>])</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Encode categoricals for survival time generation ---</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>env_effect <span class="op">=</span> np.where(environment <span class="op">==</span> <span class="st">'indoor'</span>, <span class="fl">1.0</span>,</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>             np.where(environment <span class="op">==</span> <span class="st">'outdoor'</span>, <span class="fl">0.85</span>, <span class="fl">0.65</span>))</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>mfr_effect <span class="op">=</span> np.where(manufacturer <span class="op">==</span> <span class="st">'A'</span>, <span class="fl">1.0</span>,</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>             np.where(manufacturer <span class="op">==</span> <span class="st">'B'</span>, <span class="fl">0.9</span>, <span class="fl">0.75</span>))</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a><span class="co"># --- True Weibull parameters ---</span></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Scale theta depends on covariates</span></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Higher stress covariates -&gt; smaller theta -&gt; shorter survival</span></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>gamma_true <span class="op">=</span> <span class="fl">2.0</span></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>theta_true <span class="op">=</span> (</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>    <span class="dv">300</span></span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>    <span class="op">*</span> env_effect</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>    <span class="op">*</span> mfr_effect</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>    <span class="op">/</span> (</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>        <span class="dv">1</span></span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>        <span class="op">+</span> <span class="fl">0.03</span> <span class="op">*</span> machine_age</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>        <span class="op">+</span> <span class="fl">0.15</span> <span class="op">*</span> usage_intensity</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>        <span class="op">+</span> <span class="fl">0.008</span> <span class="op">*</span> operating_temp</span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>        <span class="op">+</span> <span class="fl">0.10</span> <span class="op">*</span> load_factor</span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>        <span class="op">+</span> <span class="fl">0.0001</span> <span class="op">*</span> rpm</span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>        <span class="op">+</span> <span class="fl">0.05</span> <span class="op">*</span> vibration_level</span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a>        <span class="op">+</span> <span class="fl">0.10</span> <span class="op">*</span> oil_quality</span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>        <span class="op">-</span> <span class="fl">0.02</span> <span class="op">*</span> maintenance_count  <span class="co"># more maintenance -&gt; longer survival</span></span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Generate Weibull failure times via inverse CDF ---</span></span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a>u <span class="op">=</span> np.random.uniform(<span class="dv">0</span>, <span class="dv">1</span>, n)</span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a>T <span class="op">=</span> theta_true <span class="op">*</span> (<span class="op">-</span>np.log(<span class="dv">1</span> <span class="op">-</span> u))<span class="op">**</span>(<span class="dv">1</span> <span class="op">/</span> gamma_true)</span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Random right censoring ---</span></span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a>C <span class="op">=</span> np.random.uniform(<span class="dv">50</span>, <span class="dv">400</span>, n)</span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Observed time and event indicator ---</span></span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a>Y     <span class="op">=</span> np.minimum(T, C)</span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a>delta <span class="op">=</span> (T <span class="op">&lt;=</span> C).astype(<span class="bu">int</span>)</span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-62"><a href="#cb2-62" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Build dataframe ---</span></span>
<span id="cb2-63"><a href="#cb2-63" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb2-64"><a href="#cb2-64" aria-hidden="true" tabindex="-1"></a>    <span class="st">'machine_id'</span>:         [<span class="ss">f'M</span><span class="sc">{</span>i<span class="op">+</span><span class="dv">1</span><span class="sc">:04d}</span><span class="ss">'</span> <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n)],</span>
<span id="cb2-65"><a href="#cb2-65" aria-hidden="true" tabindex="-1"></a>    <span class="st">'machine_age'</span>:        machine_age.<span class="bu">round</span>(<span class="dv">2</span>),</span>
<span id="cb2-66"><a href="#cb2-66" aria-hidden="true" tabindex="-1"></a>    <span class="st">'usage_intensity'</span>:    usage_intensity.<span class="bu">round</span>(<span class="dv">2</span>),</span>
<span id="cb2-67"><a href="#cb2-67" aria-hidden="true" tabindex="-1"></a>    <span class="st">'operating_temp'</span>:     operating_temp.<span class="bu">round</span>(<span class="dv">2</span>),</span>
<span id="cb2-68"><a href="#cb2-68" aria-hidden="true" tabindex="-1"></a>    <span class="st">'load_factor'</span>:        load_factor.<span class="bu">round</span>(<span class="dv">2</span>),</span>
<span id="cb2-69"><a href="#cb2-69" aria-hidden="true" tabindex="-1"></a>    <span class="st">'rpm'</span>:                rpm.<span class="bu">round</span>(<span class="dv">0</span>).astype(<span class="bu">int</span>),</span>
<span id="cb2-70"><a href="#cb2-70" aria-hidden="true" tabindex="-1"></a>    <span class="st">'vibration_level'</span>:    vibration_level.<span class="bu">round</span>(<span class="dv">3</span>),</span>
<span id="cb2-71"><a href="#cb2-71" aria-hidden="true" tabindex="-1"></a>    <span class="st">'oil_quality'</span>:        oil_quality.<span class="bu">round</span>(<span class="dv">3</span>),</span>
<span id="cb2-72"><a href="#cb2-72" aria-hidden="true" tabindex="-1"></a>    <span class="st">'maintenance_count'</span>:  maintenance_count.astype(<span class="bu">int</span>),</span>
<span id="cb2-73"><a href="#cb2-73" aria-hidden="true" tabindex="-1"></a>    <span class="st">'environment'</span>:        environment,</span>
<span id="cb2-74"><a href="#cb2-74" aria-hidden="true" tabindex="-1"></a>    <span class="st">'manufacturer'</span>:       manufacturer,</span>
<span id="cb2-75"><a href="#cb2-75" aria-hidden="true" tabindex="-1"></a>    <span class="st">'observed_time'</span>:      Y.<span class="bu">round</span>(<span class="dv">2</span>),</span>
<span id="cb2-76"><a href="#cb2-76" aria-hidden="true" tabindex="-1"></a>    <span class="st">'event_observed'</span>:     delta</span>
<span id="cb2-77"><a href="#cb2-77" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb2-78"><a href="#cb2-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-79"><a href="#cb2-79" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Summary ---</span></span>
<span id="cb2-80"><a href="#cb2-80" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Total machines    : </span><span class="sc">{</span>n<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-81"><a href="#cb2-81" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Observed failures : </span><span class="sc">{</span>delta<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ss"> (</span><span class="sc">{</span><span class="dv">100</span><span class="op">*</span>delta<span class="sc">.</span>mean()<span class="sc">:.1f}</span><span class="ss">%)"</span>)</span>
<span id="cb2-82"><a href="#cb2-82" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Censored          : </span><span class="sc">{</span>(<span class="dv">1</span><span class="op">-</span>delta)<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ss"> (</span><span class="sc">{</span><span class="dv">100</span><span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>delta)<span class="sc">.</span>mean()<span class="sc">:.1f}</span><span class="ss">%)"</span>)</span>
<span id="cb2-83"><a href="#cb2-83" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Mean observed time: </span><span class="sc">{</span>Y<span class="sc">.</span>mean()<span class="sc">:.1f}</span><span class="ss"> hours"</span>)</span>
<span id="cb2-84"><a href="#cb2-84" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">First 10 rows:"</span>)</span>
<span id="cb2-85"><a href="#cb2-85" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.head(<span class="dv">10</span>).to_string(index<span class="op">=</span><span class="va">False</span>))</span>
<span id="cb2-86"><a href="#cb2-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-87"><a href="#cb2-87" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Save ---</span></span>
<span id="cb2-88"><a href="#cb2-88" aria-hidden="true" tabindex="-1"></a>os.makedirs(<span class="st">'../../data'</span>, exist_ok<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-89"><a href="#cb2-89" aria-hidden="true" tabindex="-1"></a>df.to_csv(<span class="st">'../../data/machine_fleet.csv'</span>, index<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb2-90"><a href="#cb2-90" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Dataset saved to ../../data/machine_fleet.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Total machines    : 1000
Observed failures : 886 (88.6%)
Censored          : 114 (11.4%)
Mean observed time: 81.4 hours

First 10 rows:
machine_id  machine_age  usage_intensity  operating_temp  load_factor  rpm  vibration_level  oil_quality  maintenance_count environment manufacturer  observed_time  event_observed
     M0001         5.62             0.78           75.70         0.77 1930            4.240        0.648                 10     outdoor            A         111.39               1
     M0002        14.26             1.31           74.82         0.86 2514            4.998        0.172                 16     outdoor            A          68.56               1
     M0003        10.98             1.81          114.38         0.48 2400            8.618        0.872                  4      indoor            C          49.03               1
     M0004         8.98             1.60           74.97         0.74  885            3.730        0.613                  6       harsh            A          88.65               1
     M0005         2.34             1.71           76.32         0.70  873            8.762        0.157                 18      indoor            B         205.67               1
     M0006         2.34             1.49          105.56         0.88 1170            1.337        0.962                 14       harsh            B          69.69               1
     M0007         0.87             1.54           86.98         0.93 1403            7.880        0.518                  2     outdoor            B          79.77               0
     M0008        12.99             1.77          106.60         0.31 1521            8.552        0.073                 14      indoor            B          28.99               1
     M0009         9.02             0.87           63.92         0.77 2199            2.227        0.627                  4       harsh            B          37.09               1
     M0010        10.62             1.23           89.25         0.34  642            4.588        0.253                 11      indoor            A         106.60               1

Dataset saved to ../../data/machine_fleet.csv</code></pre>
</div>
</div>
<p>We generate a synthetic fleet of 1000 machines, each with 8 continuous and 2 categorical covariates representing realistic machine characteristics — age, operating temperature, vibration level, manufacturer, and so on. The true failure times are drawn from a Weibull distribution with shape <span class="math inline">\(\gamma = 2.0\)</span> and a scale parameter <span class="math inline">\(\theta\)</span> that depends on the covariates — higher stress (temperature, vibration, load) shrinks <span class="math inline">\(\theta\)</span> and shortens expected lifetime, while more maintenance history extends it.</p>
<p>For now, we work only with the observed times — whether the machine failed or was censored. But in reality, a machine’s lifetime depends on its physical characteristics — how old it is, how hard it runs, the temperature it operates at, how well it has been maintained. Modeling the relationship between these characteristics and the failure time is exactly what survival regression models like the Cox Proportional Hazards model are built to do — and that is where we are headed.</p>
<p>Now, we will fit a Weibull to the observed times with <code>lifelines</code>. Here is the piece of code.</p>
<div id="cell-weibull-fit-censored" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> lifelines <span class="im">import</span> WeibullFitter</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>wf <span class="op">=</span> WeibullFitter()</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">'../../data/machine_fleet.csv'</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>wf.fit(df[<span class="st">'observed_time'</span>], event_observed<span class="op">=</span>df[<span class="st">'event_observed'</span>])</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>wf.print_summary()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="weibull-fit-censored" class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">model</th>
<td>lifelines.WeibullFitter</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">number of observations</th>
<td>1000</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">number of events observed</th>
<td>886</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">log-likelihood</th>
<td>-4684.21</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">hypothesis</th>
<td>lambda_ != 1, rho_ != 1</td>
</tr>
</tbody>
</table>

</div>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="min-width: 12px"></th>
<th data-quarto-table-cell-role="th" style="min-width: 12px">coef</th>
<th data-quarto-table-cell-role="th" style="min-width: 12px">se(coef)</th>
<th data-quarto-table-cell-role="th" style="min-width: 12px">coef lower 95%</th>
<th data-quarto-table-cell-role="th" style="min-width: 12px">coef upper 95%</th>
<th data-quarto-table-cell-role="th" style="min-width: 12px">cmp to</th>
<th data-quarto-table-cell-role="th" style="min-width: 12px">z</th>
<th data-quarto-table-cell-role="th" style="min-width: 12px">p</th>
<th data-quarto-table-cell-role="th" style="min-width: 12px">-log2(p)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">lambda_</th>
<td>97.26</td>
<td>1.80</td>
<td>93.72</td>
<td>100.79</td>
<td>1.00</td>
<td>53.41</td>
<td>&lt;0.005</td>
<td>inf</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">rho_</th>
<td>1.86</td>
<td>0.05</td>
<td>1.76</td>
<td>1.95</td>
<td>1.00</td>
<td>17.69</td>
<td>&lt;0.005</td>
<td>230.18</td>
</tr>
</tbody>
</table>
<br><div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">AIC</th>
<td>9372.42</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>886 out of 1000 machines failed during the study- an 88.6% event rate with 11.4% censored. The fitted shape parameter <span class="math inline">\(\hat{\gamma} = 1.86\)</span> is close to but not exactly the true value of <span class="math inline">\(\gamma = 2.0\)</span>. This is expected — we are fitting a single Weibull to all 1000 machines while ignoring the fact that each machine has a different <span class="math inline">\(\theta\)</span> driven by its covariates. By fitting a single Weibull, we are forcing one distribution to describe a heterogeneous fleet of machines. This is precisely why survival regression methods exist- to model how machine characteristics influence lifetime. We will get there eventually. But first, let’s assess how well this naive fit describes the data using diagnostic tools.</p>
</section>
</section>
<section id="diagnostic-tool-q-q-plot" class="level3">
<h3 class="anchored" data-anchor-id="diagnostic-tool-q-q-plot">Diagnostic Tool: Q-Q Plot</h3>
<p>The Q-Q plot is a graphical method to display whether a dataset follows a particular distribution or whether two datasets come from the same population. For our purposes, we are testing if the dataset comes from a particular Weibull or not. Note that the game is rigged- we simulated data to follow a particular Weibull, so we already know the answer. But the Q-Q plot is a diagnostic tool we will use repeatedly on real data where we do not know the answer.</p>
<p>The basic idea of the Q-Q plot is to compare theoretical quantiles vs empirical quantiles. If the data fits a particular Weibull, these quantiles should match and the points should fall on a straight line. Here is how we’ll build the Q-Q plot for the Weibull step by step.</p>
<section id="step-1-theoretical-quantile" class="level4">
<h4 class="anchored" data-anchor-id="step-1-theoretical-quantile">Step 1: Theoretical Quantile</h4>
</section>
<section id="step-1-theoretical-quantiles" class="level4">
<h4 class="anchored" data-anchor-id="step-1-theoretical-quantiles">Step 1: Theoretical Quantiles</h4>
<p>Recall that the <span class="math inline">\(p\)</span>-th quantile of a probability distribution is the value <span class="math inline">\(t_p\)</span> such that <span class="math inline">\(P(T \leq t_p) = p\)</span> where <span class="math inline">\(p \in [0, 1]\)</span>. For instance, the 0.5 quantile (also called the 50th percentile) is the median. Let’s derive the theoretical quantiles of the Weibull distribution.</p>
<p>We want to find <span class="math inline">\(t_p\)</span> such that <span class="math inline">\(F(t_p) = p\)</span>. If <span class="math inline">\(T \sim \text{Weibull}(\theta, \gamma)\)</span>, then:</p>
<p><span class="math display">\[1 - \exp\left\{-\left(\frac{t_p}{\theta}\right)^\gamma\right\} = p\]</span></p>
<p>Rearranging:</p>
<p><span class="math display">\[1 - p = \exp\left\{-\left(\frac{t_p}{\theta}\right)^\gamma\right\}\]</span></p>
<p>Taking logarithms of both sides:</p>
<p><span class="math display">\[-\ln(1-p) = \left(\frac{t_p}{\theta}\right)^\gamma\]</span></p>
<p><span class="math display">\[\ln\left(\frac{1}{1-p}\right) = \left(\frac{t_p}{\theta}\right)^\gamma\]</span></p>
<p>Taking the <span class="math inline">\(\gamma\)</span>-th root:</p>
<p><span class="math display">\[\boxed{t_p = \theta \left[\ln\left(\frac{1}{1-p}\right)\right]^{1/\gamma}}\]</span></p>
<p>This is the quantile function (inverse CDF) of the Weibull distribution. Given a probability <span class="math inline">\(p\)</span>, it tells us the time by which a fraction <span class="math inline">\(p\)</span> of systems are expected to have failed.</p>
<p>Here is a special value: <span class="math inline">\(p = 1 - \frac{1}{e}\)</span>. Substituting into the quantile function:</p>
<p><span class="math display">\[t_p = \theta \left[\ln\left(\frac{1}{1-(1-\frac{1}{e})}\right)\right]^{1/\gamma} = \theta \left[\ln\left(\frac{1}{\frac{1}{e}}\right)\right]^{1/\gamma} = \theta \left[\ln(e)\right]^{1/\gamma} = \theta \cdot 1^{1/\gamma} = \theta\]</span></p>
<p>So <span class="math inline">\(t_{1-1/e} = \theta\)</span> — the scale parameter <span class="math inline">\(\theta\)</span> is exactly the <span class="math inline">\((1 - 1/e) \approx 63.2\)</span>th percentile of the Weibull distribution, regardless of the shape parameter <span class="math inline">\(\gamma\)</span>. This confirms what we noted earlier: by time <span class="math inline">\(\theta\)</span>, approximately 63.2% of systems will have failed.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/madhavpr191221\.github\.io\/blog");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>