{
  "hash": "450453138dbf57b00cf268d0ff00d182",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Part 4: The Kaplan-Meier Estimator\"\nauthor: \"Madhav Prashanth Ramachandran\"\ndate: \"2026-06-02\"\ncategories: [survival analysis, statistics]\n---\n\n## Recap of Part 3 and What's Coming in Part 4\n\nIn [**Part 3**](https://madhavpr191221.github.io/blog/posts/part-3-fitting-survival-distributions/), we derived the likelihood function for censored data \nfrom first principles, fit a Weibull distribution to our synthetic machine fleet, \nand assessed the quality of that fit using two diagnostic tools — the Q-Q plot, \nwhich told the story visually, and the K-S test, which put a number on it. \nWe ended with a sobering observation: a single Weibull is not enough for a \nheterogeneous fleet. The K-S statistic $D_n = 0.067$ translated into a ₹6 crore \ncost swing — and we couldn't identify which machines were responsible without \nmodeling the effect of their individual characteristics on failure time.\n\nBefore we get to regression models, we need a better estimator of the survival \nfunction itself — one that handles censored data naturally and doesn't require us \nto assume any parametric form for the distribution of failure times. This is the \nsubject of Part 4.\n\n\n## The Kaplan-Meier Estimator\n\nThis part introduces the OG estimator of the survival function, the **Kaplan-Meier estimator**, and derives it from first principles. Most survival analysis blogs introduce this estimator in the very beginning before any groundwork. But we like first principles, and this is how we will derive it. We will also prove Greenwood’s formula for the variance of the Kaplan-Meier (KM) estimator, and handle tied failure times rigorously. Finally, we will apply both to our machine fleet dataset. Let’s get started!\n\nIn survival analysis and reliability engineering, we don't see all the failure times of the units under study. Some units may still function at the end of the study, while others may be lost to follow-up. This is known as right censoring. Note that other censoring types like left and interval censoring also exist, but we will focus on right censoring as it is the most common type in survival analysis. Can you still estimate the survival function of the population with this incomplete data? The Kaplan-Meier estimator provides a way to do just that. It is a non-parametric estimator of the survival function that can handle right-censored data.\n\n\nHere is the setup. You have a non-negative random variable $T$ representing the \ntime until an event of interest — failure of a machine, say. You have a sample of \n$n$ i.i.d. observations, but some are right-censored. Formally, you observe pairs \n$\\{(Y_i, \\delta_i)\\}$ for $i = 1, 2, \\ldots, n$, where \n$Y_i = \\min(T_i, C_i)$ is the observed time and \n$\\delta_i = \\mathbf{1}\\{T_i \\leq C_i\\}$ is the event indicator — 1 if the \nfailure was observed, 0 if censored.\n\n\nLet $t_{(1)} < t_{(2)} < \\cdots < t_{(K)}$ be the distinct failure times in the \nsample. For now, we assume no ties — no two units fail at exactly the same time. \nWe will handle ties later. What we want is to estimate the survival function at \nany time $t$ using only the observed failure times and a counting argument. \nSit tight. This is going to be fun.\n\n\n## Derivation of the Kaplan-Meier Estimator\n\nStart with the definition of the survival function:\n\n$S(t) = P(T > t)$ \nThis is the probability of surviving beyond/past time t. We will break down what it means to survive past time t into a sequence of events. \n\nTo survive past time t, you must:\n\n1. Survive past the first failure time $t_{(1)}$ (if it occurs before t)\n2. Survive past the second failure time $t_{(2)}$ (if it occurs before t)\n3. And so on, until you have survived past all the failure times that occur before t.\n\nIn other words, to survive past time t, you must survive past each of the failure times that occur before t. This can be expressed mathematically as:\n\n$S(t) = P(T > t) = P(T > t_{(1)}, T > t_{(2)}, \\ldots, T > t_{(k)})$ \n\nLet $A_j$ be the event that you survive past the j-th failure time $t_{(j)}$. Then we can rewrite the above expression as: \n\n$S(t) = P(A_1, A_2, \\ldots, A_k)$\n\nBy the chain rule of probability, we can express this joint probability as a product of conditional probabilities:\n\n$S(t) = P(A_1) \\cdot P(A_2 | A_1) \\cdot P(A_3 | A_1, A_2) \\cdots P(A_k | A_1, A_2, \\ldots, A_{k-1})$ \n\nIn words, the probability of surviving past time t is the product of the probability of surviving past the first failure time, times the probability of surviving past the second failure time given that you survived past the first, times the probability of surviving past the third failure time given that you survived past the first two, and so on. This is the crux of the Kaplan-Meier estimator. The estimator is essentially a product of conditional probabilities of surviving past each failure time, given that you have survived past all the previous failure times.\n\nThe big question now is: how do we estimate these conditional probabilities from our data?  \n\n### Estimating the Conditional Probabilities\n\nNotice one thing: If you survived past the j-th failure time $t_{(j)}, then you surely survived past all the previous failure times $t_{(1)}, t_{(2)}, ..., t_{(j-1)}$. This means that the conditional probability of surviving past the j-th failure time given that you survived past all the previous failure times is just the probability of surviving past the j-th failure time given that you were at risk just before the j-th failure time. In other words, we can simplify the conditional probabilities as follows:\n\n$P(A_j | A_1, A_2, \\ldots, A_{j-1}) = P(A_j | A_{j-1}) = P(T > t_{(j)} | T > t_{(j-1)})$ \n\n[Note that this is not the Markov assumption (if you know what that is). It is a logical consequence of the definition of the events $A_j$. It is just subset-superset logic. If you survived past $t_{(j)}$, then you must have survived past $t_{(j-1)}$, so the two events are nested. The conditional probability of surviving past $t_{(j)}$ given that you survived past all the previous failure times is just the conditional probability of surviving past $t_{(j)}$ given that you survived past $t_{(j-1)}$.]\n\nSo the probability of surviving past t_{(j)} can be written as a simplified conditional probability that only depends on the previous failure time. That is\n\n$S(t)= P(T > t_{(1)}) \\cdot P(T > t_{(2)} | T > t_{(1)}) \\cdot P(T > t_{(3)} | T > t_{(2)}) \\cdots P(T > t_{(k)} | T > t_{(k-1)})$\n\nThe survival function is a product of conditional probabilities — the probability \nof surviving past each failure time, given survival up to the previous one. \nThe question is how to estimate each factor from the data.\n\n## The Risk Set\n\nWe need a definition. A machine or a unit is said to be \"at risk\" at time t if it has not yet failed or been censored by time t. In other words, it is still in the study and has the potential to fail in the future. Formally, the **risk set** at time t, denoted by R(t), is the set of all individuals who are at risk at time t. Mathematically, we can define the risk set as follows:\n\n$R(t) = \\{i : Y_i \\geq t\\} = \\{i: min(T_i, C_i) \\geq t\\} = \\{i: T_i \\geq t \\text{ and } C_i \\geq t\\}$ \n\nThat is, the risk set at time t consists of those units who are still under observation at time t and have not yet experienced the event of interest (failure) or been censored. The size of the risk set just before the $j$-th \nfailure time is:\n\n$$n_j = |R(t_{(j)})| = |\\{i : Y_i \\geq t_{(j)}\\}|$$\n\nNote the $\\geq$: units that fail exactly at $t_{(j)}$ are counted as at risk \njust before $t_{(j)}$. They are in the risk set, and then they leave it.\n\n## Counting Argument for Estimating the Conditional Probabilities\n\n$P(T > t_{(j)} | T > t_{(j-1)})$ is the probability of surviving past time $t_{(j)}$ given that you survived past time $t_{(j-1)}$. This is equivalent to 1 minus the probability of failing at time $t_{(j)}$ given that you survived past time $t_{(j-1)}$. In other words, we can write:\n\n$P(T > t_{(j)} | T > t_{(j-1)}) = 1 - P(T \\leq t_{(j)} | T > t_{(j-1)})$ \n\nUsing the definition of conditional probability, we can express the above probability as follows:\n\n$P(T \\leq t_{(j)} \\mid T > t_{(j-1)}) = \\frac{P(T \\leq t_{(j)},\\ T > t_{(j-1)})}{P(T > t_{(j-1)})}$ = $\\frac{P(t_{(j-1)} < T \\leq t_{(j)})}{P(T > t_{(j-1)})}$ \n\n\nWe are working with realizations (observed data), not the continuous random variable $T$. We know that for any continuous random variable, the probability of it taking any specific value, say $t_0$, is zero. So, $P(T = t_0) = 0$ for any $t_0$. But we are working with observed data, and in our observed data, we do have some units that fail at specific times. So, we can treat the observed failure times as discrete points where the probability of failure is non-zero. This is a common approach in survival analysis when dealing with real-world data. In the data, exactly $d_j$ units failed at the recorded failure time $t_{(j)}$. This is not a statement about the (continuous) random variable $T$, but rather a statement about the observed data. So the event \n$\\{T \\leq t_{(j)},\\ T > t_{(j-1)}\\}$ — failure somewhere in \n$(t_{(j-1)},\\ t_{(j)}]$ — collapses to failure exactly at $t_{(j)}$:\n\n$P(T \\leq t_{(j)},\\ T > t_{(j-1)}) = P(T = t_{(j)})$\n\nThe conditional probability becomes: \n\n$P(T \\leq t_{(j)} \\mid T > t_{(j-1)}) = \\frac{P(T = t_{(j)})}{P(T > t_{(j-1)})}$ \n\nNow we can estimate the numerator and denominator from the data using a counting argument.\n\n**Numerator:** $P(T = t_{(j)})$ - the probability that a randomly chosen unit fails exactly at time $t_{j}$. In the sample of $n$ units, $d_j$ units failed at time $t_{(j)}$. Thus, the failure probability at time $t_{j}$ is simply $\\frac{d_j}{n}$. \n\n\n**Denominator:** $P(T > t_{(j-1)})$- the probability that a randomly chosen unit survives past time $t_{(j-1)}$. Since there are no failures in the open interval $(t_{(j-1)},\\ t_{(j)})$, a unit that survived past $t_{(j-1)}$ is still at \nrisk just before $t_{(j)}$ — and vice versa. The two conditions are equivalent. In the sample, exactly $n_j$ units are at risk just before $t_{(j)}$, so the probability of surviving past $t_{(j-1)}$ is $\\frac{n_j}{n}$.\n\nPutting it all together, we get:\n\n$P(T > t_{(j)} | T > t_{(j-1)}) = 1 - \\frac{P(T = t_{(j)})}{P(T > t_{(j-1)})} = 1 - \\frac{\\frac{d_j}{n}}{\\frac{n_j}{n}} = 1 - \\frac{d_j}{n_j}$ \n\nExcellent! We have an estimate for the conditional probability of surviving \npast each failure time. Plugging back into our expression for $S(t)$:\n\n### The Kaplan-Meier Estimator — Final Form\n\nPlugging the estimated conditional probabilities back into the product formula for $S(t)$, we get:\n$$\\hat{S}(t) = \\prod_{t_{(j)} \\leq t} \\left(1 - \\frac{d_j}{n_j}\\right)$$\n\nThis is the **Kaplan-Meier estimator** — derived from nothing more than the \ndefinition of the survival function, the chain rule of probability, and a \ncounting argument. No distributional assumptions, no parameters to fit. \nThe hat on $\\hat{S}(t)$ is a reminder that this is an estimator of the true \nsurvival function, not the truth itself. The estimator was introduced by \nEdward Kaplan and Paul Meier in a 1958 paper in the Journal of the American \nStatistical Association — one of the most cited papers in all of statistics. \nIt's titled \"Nonparametric Estimation from Incomplete Observations\" — a perfect description of what we just did. Here is the [link](https://web.stanford.edu/~lutian/coursepdf/KMpaper.pdf) to the original paper.\n\nHere's some code to compute the Kaplan-Meier estimator in Python:\n\n::: {#cell-fig-km-fleet .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom lifelines import KaplanMeierFitter\n\ndf = pd.read_csv('../../data/machine_fleet.csv')\n\nkmf = KaplanMeierFitter()\nkmf.fit(df['observed_time'], event_observed=df['event_observed'], label='Machine Fleet')\nplt.close('all')    # <-- here, before any plotting\n\n\n# --- Plot ---\nfig, ax = plt.subplots(figsize=(10, 5))\n\nkmf.plot_survival_function(\n    ax=ax,\n    ci_show=True,\n    color='steelblue',\n    ci_alpha=0.15\n)\n\nax.set_xlabel('Time (hours)', fontsize=12)\nax.set_ylabel(r'$\\hat{S}(t)$', fontsize=12)\nax.set_title('Kaplan-Meier Survival Estimate — Machine Fleet (n=1000)', fontsize=13)\nax.axhline(y=0.5, color='firebrick', linestyle='--', linewidth=0.8, label='Median survival')\nax.legend(fontsize=11)\nax.grid(True, alpha=0.3)\n\nplt.tight_layout()\nplt.show()\n\nprint(f\"Median survival time : {kmf.median_survival_time_:.1f} hours\")\nprint(f\"Total machines       : {len(df)}\")\nprint(f\"Observed failures    : {df['event_observed'].sum()} ({100*df['event_observed'].mean():.1f}%)\")\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/fig-km-fleet-output-1.png){#fig-km-fleet width=948 height=470}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nMedian survival time : 78.5 hours\nTotal machines       : 1000\nObserved failures    : 886 (88.6%)\n```\n:::\n:::\n\n\nThe KM curve tells a clear story. The fleet degrades rapidly in the first \n100 hours — by $t = 78.5$ hours, half the machines have already failed. \nThis is the **median survival time**: the time at which $\\hat{S}(t)$ crosses \n0.5. Beyond 200 hours, the curve flattens out and our estimate of the survival function becomes more uncertain. \n\nNotice the shaded band around the curve. This is the pointwise confidence \ninterval for $\\hat{S}(t)$, and it is not free — it requires an estimate of \nthe variance of $\\hat{S}(t)$. That variance estimate is **Greenwood's formula**, \nand deriving it is exactly what we do next.\n\n\n## Greenwood's Formula for the Variance of the Kaplan-Meier Estimator\n\nSince the conditional probabilities in the product formula for $\\hat{S}(t)$ are estimated from the data, $\\hat{S}(t)$ is a random variable. Therefore it has an uncertainty associated with it, which we can quantify using its variance. Greenwood's formula gives us a way to estimate the variance of the Kaplan-Meier estimator at any time t. We want to know how much $\\hat{S}(t)$ varies from sample to sample due to random sampling variability. This is crucial for constructing confidence intervals and performing standard hypothesis tests to quantify uncertainty in our estimates. We will derive Greenwood's formula from first principles. The derivation uses two applications of the delta method. If that's new to \nyou, there's a short detour below — it's worth knowing. If it's familiar, you'll enjoy seeing it applied here.\n\nLet's start with the expression for the Kaplan-Meier estimator:\n\n$$\\hat{S}(t) = \\prod_{t_{(j)} \\leq t} \\left(1 - \\frac{d_j}{n_j}\\right)$$\n\nSet $\\hat{p}_k = \\frac{d_k}{n_k}$ for $k = 1, 2, \\ldots, K$. Then we can rewrite the Kaplan-Meier estimator as follows:\n\n$$\\hat{S}(t) = \\prod_{t_{(j)} \\leq t} (1 - \\hat{p}_j)$$\n\nTaking the natural logarithm of both sides, we get:\n\n$$\\ln \\hat{S}(t) = \\sum_{t_{(j)} \\leq t} \\ln (1 - \\hat{p}_j)$$ \n\nTaking variance, we have \n\n$$\\text{Var}(\\ln \\hat{S}(t)) = \\text{Var}\\left(\\sum_{t_{(j)} \\leq t} \\ln (1 - \\hat{p}_j)\\right)$$\n\nQuestion: Are the terms $\\ln (1 - \\hat{p}_j)$ independent of each other? \nThe answer is yes. Because the failure times are distinct and the $\\hat{p}_j$ are based on disjoint sets of units (the risk sets at different failure times), the $\\hat{p}_j$ are independent random variables. Therefore, the terms $\\ln (1 - \\hat{p}_j)$ are also independent. For independent random variables, the variance of a sum is the sum of the variances. Thus, we can write:\n\n$$\\text{Var}(\\ln \\hat{S}(t)) = \\sum_{t_{(j)} \\leq t} \\text{Var}(\\ln (1 - \\hat{p}_j))$$\n\nCan we compute $\\text{Var}({p}_j)$? Yes, we can. $\\hat{p}_j$ is the sample proportion of failures at time $t_{(j)}$ among the $n_j$ units at risk just before $t_{(j)}$. Under the assumption of independent failures, $\\hat{p}_j$ follows a binomial distribution with parameters $n_j$ and $p_j$, where $p_j$ is the true probability of failure at time $t_{(j)}$. The variance of a binomial random variable is given by:\n\n$$\\text{Var}(\\hat{p}_j) = \\frac{p_j (1 - p_j)}{n_j}$$ \n\nAnd replacing $p_j$ with its estimate $\\hat{p}_j$, we get:\n$$\\text{Var}(\\hat{p}_j) = \\frac{\\hat{p}_j (1 - \\hat{p}_j)}{n_j}$$\n\nHow do we get from $\\text{Var}(\\hat{p}_j)$ to $\\text{Var}(\\ln (1 - \\hat{p}_j))$? This is where the delta method comes in. \n\n### The Delta Method and its Application to Greenwood's Formula\n\nLet $X_{n}$ be a sequence of random variables such that $\\sqrt{n}(X_{n} - \\theta) \\xrightarrow{d} N(0, \\sigma^2)$ as $n \\to \\infty$, where N(0, $\\sigma^2$) is a normal distribution with mean 0 and variance $\\sigma^2$. Let $g$ be a function that is differentiable at $\\theta$ with $g'(\\theta) \\neq 0$. Then, by the delta method, we have:\n\n$$\\sqrt{n}(g(X_{n}) - g(\\theta)) \\xrightarrow{d} N(0, (g'(\\theta))^2 \\sigma^2)$$\n\nThis means that the variation of $g(X_{n})$ is approximately g'($\\theta$) times the variation of $X_{n}$ for large n. The delta method allows us to find the asymptotic distribution of a function of a random variable, given the asymptotic distribution of the random variable itself.\n\nWhat does the $(d)$ superscript mean? This is a special type of convergence of random variables known as **convergence in distribution** which in simple terms says that the distribution of the random variable on the left-hand side converges to the distribution on the right-hand side as n goes to infinity. This is exactly what the Central Limit Theorem tells us about the distribution of sample means. A certain function of the sample mean converges in distribution to a normal distribution as the sample size increases. The delta method is a generalization of the Central Limit Theorem that allows us to find the asymptotic distribution of a function of a random variable, given the asymptotic distribution of the random variable itself. Is it worth going into the details of the proof of the delta method? Probably not. You can find the proof in any mathematical statistics textbook. The key idea is to use some technical theorems to show that the distribution of $g(X_{n})$ converges to a normal distribution with mean $g(\\theta)$ and variance $(g'(\\theta))^2 \\sigma^2$. Do not worry if this is not clear. Go look it up!! \n\nNow we can apply the delta method to find $\\text{Var}(\\ln (1 - \\hat{p}_j))$. Let $X_{n} = \\hat{p}_j$, $\\theta = p_j$, and $g(x) = \\ln(1 - x)$. Then we have:\n$$g'(\\theta) = g'(p_j) = -\\frac{1}{1 - p_j}$$\n\nApplying the delta method, we get:\n$$\\text{Var}(\\ln (1 - \\hat{p}_j)) = \\left(\\frac{1}{(1 - p_j)^2}\\right) \\text{Var}(\\hat{p}_j) = \\left(\\frac{1}{(1 - p_j)^2}\\right) \\frac{p_j (1 - p_j)}{n_j} = \\frac{p_j}{n_j (1 - p_j)}$$\n\nTo get an estimate of $\\text{Var}(\\ln (1 - \\hat{p}_j))$, we replace $p_j$ with its estimate $\\hat{p}_j$:\n$$\\widehat{\\text{Var}}(\\ln (1 - \\hat{p}_j)) = \\frac{\\hat{p}_j}{n_j (1 - \\hat{p}_j)}$$\n\nFinally, plugging this back into our expression for $\\text{Var}(\\ln \\hat{S}(t))$, we get:\n\n$$\\widehat{\\text{Var}}(\\ln \\hat{S}(t)) = \\sum_{t_{(j)} \\leq t} \\frac{\\hat{p}_j}{n_j (1 - \\hat{p}_j)}$$ \n\nWe can simplify this expression further by noting that $\\hat{p}_j = \\frac{d_j}{n_j}$ and $1 - \\hat{p}_j = 1 - \\frac{d_j}{n_j} = \\frac{n_j - d_j}{n_j}$. Substituting these into the formula, we get:\n\n$$\\widehat{\\text{Var}}(\\ln \\hat{S}(t)) = \\sum_{t_{(j)} \\leq t} \\frac{\\frac{d_j}{n_j}}{n_j \\cdot \\frac{n_j - d_j}{n_j}} = \\sum_{t_{(j)} \\leq t} \\frac{d_j}{n_j (n_j - d_j)}$$\n\nDo we have what we came from? Not quite. We have the variance of $\\ln \\hat{S}(t)$, but we want the variance of $\\hat{S}(t)$. No problem. We can use the delta method again to find $\\text{Var}(\\hat{S}(t))$ from $\\text{Var}(\\ln \\hat{S}(t))$. \nLet $X_{n} = \\ln \\hat{S}(t)$, $\\theta = \\ln S(t)$, and $g(x) = e^x$. Then we have:\n$$g'(\\theta) = g'(\\ln S(t)) = e^{\\ln S(t)} = S(t)$$\n\n\n$$\\text{Var}(\\hat{S}(t)) \\approx (S(t))^2 \\cdot \\text{Var}(\\ln \\hat{S}(t))$$\n\nReplacing $S(t)$ with $\\hat{S}(t)$:\n\n$$\\widehat{\\text{Var}}(\\hat{S}(t)) = [\\hat{S}(t)]^2 \\sum_{t_{(j)} \\leq t} \n\\frac{d_j}{n_j(n_j - d_j)}$$\n\n\nThis is **Greenwood's formula** for the variance of the Kaplan-Meier estimator. It allows us to quantify the uncertainty in our estimate of the survival function at any time t, which is crucial for constructing confidence intervals and performing hypothesis tests.\n\n### Applying Greenwood's Formula to the Machine Fleet Dataset\n\n::: {#cell-fig-km-fleet-ci .cell execution_count=2}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nfrom lifelines import KaplanMeierFitter\n\ndf = pd.read_csv('../../data/machine_fleet.csv')\n\nkmf = KaplanMeierFitter()\nkmf.fit(df['observed_time'], event_observed=df['event_observed'], label='Machine Fleet')\n\n# Plotting the KM curve with confidence intervals\nfig, ax = plt.subplots(figsize=(10, 5))\n\nkmf.plot_survival_function(\n    ax=ax,\n    ci_show=True,\n    color='steelblue',\n    ci_alpha=0.15\n)\n\nax.set_xlabel('Time (hours)', fontsize=12)\nax.set_ylabel(r'$\\hat{S}(t)$', fontsize=12)\nax.set_title(\"Kaplan-Meier Estimate with Greenwood's Confidence Bands — Machine Fleet\", fontsize=13)\nax.axhline(y=0.5, color='firebrick', linestyle='--', linewidth=0.8, label='Median survival')\nax.legend(fontsize=11)\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n\n# Greenwood's formula calculations\net = kmf.event_table\nnj = et['at_risk'].values\ndj = et['observed'].values\n\nmask             = dj > 0\nnj_f             = nj[mask]\ndj_f             = dj[mask]\nt_f              = et.index[mask].values          # numpy array\n\ngreenwood_terms  = dj_f / (nj_f * (nj_f - dj_f))\ngreenwood_cumsum = np.cumsum(greenwood_terms)\n\nSt_f             = kmf.predict(t_f).values        # numpy array\ngreenwood_var    = (St_f ** 2) * greenwood_cumsum\ngreenwood_se     = np.sqrt(greenwood_var)\nci_lower         = St_f - 1.96 * greenwood_se\nci_upper         = St_f + 1.96 * greenwood_se\n\n# --- Print table ---\nprint(f\"{'Time':>8} {'n_j':>6} {'d_j':>6} {'d/n(n-d)':>12} \"\n      f\"{'S(t)':>8} {'SE':>8} {'95% CI Lower':>14} {'95% CI Upper':>14}\")\nprint(\"-\" * 82)\nfor i in range(min(15, len(t_f))):\n    print(f\"{t_f[i]:>8.1f} {nj_f[i]:>6.0f} {dj_f[i]:>6.0f} \"\n          f\"{greenwood_terms[i]:>12.6f} {St_f[i]:>8.4f} \"\n          f\"{greenwood_se[i]:>8.4f} {ci_lower[i]:>14.4f} \"\n          f\"{ci_upper[i]:>14.4f}\")\nprint(f\"\\n(Showing first 15 failure times out of {mask.sum()} total)\")\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/fig-km-fleet-ci-output-1.png){#fig-km-fleet-ci width=948 height=470}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n    Time    n_j    d_j     d/n(n-d)     S(t)       SE   95% CI Lower   95% CI Upper\n----------------------------------------------------------------------------------\n     1.5   1000      1     0.000001   0.9990   0.0010         0.9970         1.0010\n     3.4    999      1     0.000001   0.9980   0.0014         0.9952         1.0008\n     5.2    998      1     0.000001   0.9970   0.0017         0.9936         1.0004\n     5.4    997      1     0.000001   0.9960   0.0020         0.9921         0.9999\n     5.6    996      1     0.000001   0.9950   0.0022         0.9906         0.9994\n     5.9    995      1     0.000001   0.9940   0.0024         0.9892         0.9988\n     6.4    994      1     0.000001   0.9930   0.0026         0.9878         0.9982\n     6.4    993      1     0.000001   0.9920   0.0028         0.9865         0.9975\n     7.9    992      1     0.000001   0.9910   0.0030         0.9851         0.9969\n     7.9    991      1     0.000001   0.9900   0.0031         0.9838         0.9962\n     8.3    990      1     0.000001   0.9890   0.0033         0.9825         0.9955\n     8.9    989      1     0.000001   0.9880   0.0034         0.9813         0.9947\n     9.1    988      1     0.000001   0.9870   0.0036         0.9800         0.9940\n     9.3    987      1     0.000001   0.9860   0.0037         0.9787         0.9933\n    10.1    986      1     0.000001   0.9850   0.0038         0.9775         0.9925\n\n(Showing first 15 failure times out of 859 total)\n```\n:::\n:::\n\n\n### Confidence Intervals for the Kaplan-Meier Estimator\n\nWe have an estimator $\\hat{S}(t)$ and, thanks to Greenwood's formula, we \nhave an estimate of its variance. The square root of the variance is its standard error. A single number (like the standard error) is hard to reason about in practice. \nSometimes, we need a **range** of the survival probability estimates. This is what a confidence interval gives us. \n\nRecall that a $(1 - \\alpha)$ confidence interval for a parameter $\\theta$ is \na random interval $[L, U]$ such that:\n\n$$P(L \\leq \\theta \\leq U) = 1 - \\alpha$$\n\nThe interval is *random* because $L$ and $U$ are computed from the data, \nwhich varies from sample to sample. The correct interpretation: if we \nrepeated the experiment many times and computed the interval each time, \n$(1-\\alpha)$ of those intervals would contain the true $\\theta$. In the \nstatistics literature, $\\alpha = 0.05$ is the standard choice, giving a \n95% confidence interval.\n\n#### A Quick Detour: CI for a Normal Random Variable\n\nLet $X_1, X_2, \\ldots, X_n$ be i.i.d. observations from $N(\\mu, \\sigma^2)$ \nwith $\\sigma^2$ known. The sample mean $\\bar{X} = \\frac{1}{n}\\sum_{i=1}^n X_i$ \nis an unbiased estimator of $\\mu$ with variance $\\sigma^2 / n$. \nStandardising:\n\n$$Z = \\frac{\\bar{X} - \\mu}{\\sigma / \\sqrt{n}} \\sim N(0, 1)$$\n\nFor a 95% interval, we need $P(-1.96 \\leq Z \\leq 1.96) = 0.95$, which gives:\n\n$$P\\left(\\bar{X} - 1.96 \\cdot \\frac{\\sigma}{\\sqrt{n}} \\leq \\mu \\leq \n\\bar{X} + 1.96 \\cdot \\frac{\\sigma}{\\sqrt{n}}\\right) = 0.95$$\n\nThe 95% CI for $\\mu$ is $\\left[\\bar{X} - 1.96 \\cdot \\frac{\\sigma}{\\sqrt{n}},\\ \n\\bar{X} + 1.96 \\cdot \\frac{\\sigma}{\\sqrt{n}}\\right]$. The structure is always \nthe same: estimate $\\pm$ $z$-score $\\times$ standard error.\n\n#### The Naive CI for $\\hat{S}(t)$\n\nBy analogy, and invoking the asymptotic normality of $\\hat{S}(t)$, the naive \n95% confidence interval for $S(t)$ is:\n\n$$\\hat{S}(t) \\pm 1.96 \\cdot \\widehat{\\text{SE}}[\\hat{S}(t)]$$\n\nwhere $\\widehat{\\text{SE}}[\\hat{S}(t)] = \\sqrt{\\widehat{\\text{Var}}(\\hat{S}(t))}$ \nis estimated from Greenwood's formula. Explicitly:\n\n$$\\left[\\hat{S}(t) - 1.96\\sqrt{\\widehat{\\text{Var}}(\\hat{S}(t))},\\ \n\\hat{S}(t) + 1.96\\sqrt{\\widehat{\\text{Var}}(\\hat{S}(t))}\\right]$$\n\n**Example.** Suppose $t = 250$ hours, $\\hat{S}(250) = 0.10$, and \n$\\widehat{\\text{SE}}[\\hat{S}(250)] = 0.03$. The naive 95% CI is:\n\n$$[0.10 - 1.96 \\times 0.03,\\ 0.10 + 1.96 \\times 0.03] = [0.041,\\ 0.159]$$\n\nWe are 95% confident that the true survival probability at 250 hours lies \nbetween 4.1% and 15.9%. This is a useful and interpretable statement. \n\n#### The Problem with the Naive CI\n\nThere is a catch. $S(t)$ is a probability, so it must satisfy \n$S(t) \\in [0, 1]$ for all $t$. The naive interval doesn't know this. \nNear the tails of the curve — where $\\hat{S}(t)$ is close to 0 or 1 and \nthe standard error is relatively large — the interval can breach these \nbounds. In the example above we got lucky: $[0.041, 0.159]$ stays inside \n$[0, 1]$. But at $t = 300$ hours, if $\\hat{S}(300) = 0.02$ and \n$\\widehat{\\text{SE}} = 0.015$, the naive lower bound is \n$0.02 - 1.96 \\times 0.015 = -0.009$. A survival probability of $-0.9\\%$ \nis not something the laws of probability allow, let alone something you \ncan explain to a fleet manager.\n\nThe fix is to construct the interval on a transformed scale where \n$[0, 1]$ is automatically respected, and then map back. The standard \nchoice is the **log-log transformation** — and that is what we derive next.\n\n#### The Solution: Log-Log Transformation\n\n**Step 1: Identify the transformation.**\n\nSince $\\hat{S}(t) \\in (0, 1)$, we have:\n\n$$\\hat{S}(t) \\in (0,1) \\implies \\ln \\hat{S}(t) \\in (-\\infty, 0) \n\\implies -\\ln \\hat{S}(t) \\in (0, +\\infty)$$\n\nTherefore:\n\n$$\\ln(-\\ln \\hat{S}(t)) \\in (-\\infty, +\\infty)$$\n\nThe log-log transformation maps $\\hat{S}(t)$ to the entire real line — \nno boundary constraints. This is exactly what we need.\n\n**Step 2: Variance on the log-log scale (delta method).**\n\nLet $g(s) = \\ln(-\\ln s)$. Then:\n\n$$g'(s) = \\frac{1}{s \\ln s}$$\n\n$$[g'(s)]^2 = \\frac{1}{s^2 (\\ln s)^2}$$\n\nApplying the delta method:\n\n$$\\text{Var}\\left[\\ln(-\\ln \\hat{S}(t))\\right] = \n\\frac{1}{\\hat{S}(t)^2 (\\ln \\hat{S}(t))^2} \\cdot \\text{Var}[\\hat{S}(t)]$$\n\nTaking the square root, the standard error on the log-log scale is:\n\n$$\\text{SE}\\left[\\ln(-\\ln \\hat{S}(t))\\right] = \n\\frac{\\widehat{\\text{SE}}[\\hat{S}(t)]}{|\\hat{S}(t) \\cdot \\ln \\hat{S}(t)|}$$\n\n**Step 3: CI on the log-log scale.**\n\nSet $\\theta = \\ln(-\\ln \\hat{S}(t))$. The 95% CI on the log-log scale is:\n\n$$[\\theta - w,\\ \\theta + w]$$\n\nwhere $w = 1.96 \\cdot \\text{SE}[\\theta]$.\n\n**Step 4: Transform back to the original scale.**\n\nSince $g(s) = \\ln(-\\ln s)$ has $g'(s) = \\frac{1}{s \\ln s} < 0$ for \n$s \\in (0,1)$, $g$ is strictly decreasing — and so is $g^{-1}$. \nInverting a decreasing function reverses the inequalities:\n\n$$\\theta - w < \\theta + w \\implies g^{-1}(\\theta + w) < g^{-1}(\\theta - w)$$\n\nThe inverse is $g^{-1}(z) = \\exp(-\\exp(z))$, so:\n\n$$L = g^{-1}(\\theta + w) = \\exp(-\\exp(\\theta + w))$$\n$$U = g^{-1}(\\theta - w) = \\exp(-\\exp(\\theta - w))$$\n\nSubstituting $\\exp(\\theta) = -\\ln \\hat{S}(t)$:\n\n$$L = \\exp\\!\\left(-\\exp(\\theta) \\cdot \\exp(w)\\right) \n= \\exp\\!\\left(\\ln \\hat{S}(t) \\cdot \\exp(w)\\right) \n= \\hat{S}(t)^{\\exp(w)}$$\n\n$$U = \\exp\\!\\left(-\\exp(\\theta) \\cdot \\exp(-w)\\right) \n= \\hat{S}(t)^{\\exp(-w)}$$\n\nBy definition, the lower limit L of the confidence interval is supposed to be less than the upper limit U. Does it indeed happen?\nSince $\\hat{S}(t) \\in (0,1)$ and $\\exp(w) > \\exp(-w)$, raising a number \nin $(0,1)$ to a larger exponent gives a smaller result, confirming \n$L < U$. The 95% log-log confidence interval on the original scale is:\n\n$$\\boxed{\\left[\\hat{S}(t)^{\\exp(w)},\\ \\hat{S}(t)^{\\exp(-w)}\\right]}$$\n\nwhere $w = 1.96 \\cdot \\text{SE}[\\theta]$ — the same $w$ from Step 3, \nwith $\\text{SE}[\\theta]$ expanded from Step 2:\n\n$$w = \\frac{1.96 \\cdot \\widehat{\\text{SE}}[\\hat{S}(t)]}{|\\hat{S}(t) \\cdot \\ln \\hat{S}(t)|}$$\n\nThis interval is guaranteed to stay in $(0,1)$ by construction — no \nnegative survival probabilities, no matter how sparse the risk set gets.\n\nLet's see the transformed confidence intervals in action.\n\n::: {#cell-fig-km-ci-comparison .cell execution_count=3}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nfrom lifelines import KaplanMeierFitter\n\nplt.close('all')\n\ndf = pd.read_csv('../../data/machine_fleet.csv')\n\nkmf = KaplanMeierFitter()\nkmf.fit(df['observed_time'], event_observed=df['event_observed'])\n\net               = kmf.event_table\nnj               = et['at_risk'].values\ndj               = et['observed'].values\nmask             = dj > 0\nnj_f             = nj[mask]\ndj_f             = dj[mask]\nt_f              = et.index[mask].values\nSt_f             = kmf.predict(t_f).values\n\ngreenwood_terms  = dj_f / (nj_f * (nj_f - dj_f))\ngreenwood_cumsum = np.cumsum(greenwood_terms)\nvar_St           = (St_f ** 2) * greenwood_cumsum\nse_St            = np.sqrt(var_St)\n\nnaive_lower = St_f - 1.96 * se_St\nnaive_upper = St_f + 1.96 * se_St\n\nse_theta    = se_St / (St_f * np.abs(np.log(St_f)))\nw           = 1.96 * se_theta\nll_lower    = St_f ** np.exp(w)\nll_upper    = St_f ** np.exp(-w)\n\n# Find violations\nviolation_mask  = naive_lower < 0\nviolation_times = t_f[violation_mask]\nviolation_lower = naive_lower[violation_mask]\nprint(\"Violation times    :\", violation_times)\nprint(\"naive_lower values :\", violation_lower)\n\nfig, axes = plt.subplots(1, 2, figsize=(14, 5))\n\nfor i, (ax, lower, upper, label, color) in enumerate(zip(\n    axes,\n    [naive_lower, ll_lower],\n    [naive_upper, ll_upper],\n    ['Naive (Linear) CI', 'Log-Log CI'],\n    ['tomato', 'steelblue']\n)):\n    ax.step(t_f, St_f, where='post', color='black', linewidth=1.2, label=r'$\\hat{S}(t)$')\n    ax.fill_between(t_f, lower, upper, step='post', alpha=0.25, color=color, label='95% CI')\n    ax.axhline(y=0, color='grey', linestyle=':', linewidth=0.8)\n    ax.axhline(y=1, color='grey', linestyle=':', linewidth=0.8)\n    ax.set_xlim(-2, 300)\n    ax.set_ylim(-0.15, 1.15)\n    ax.set_xlabel('Time (hours)', fontsize=12)\n    ax.set_ylabel(r'$\\hat{S}(t)$', fontsize=12)\n    ax.set_title(label, fontsize=13)\n    ax.legend(fontsize=11)\n    ax.grid(True, alpha=0.3)\n\n    if i == 0:\n        axins = ax.inset_axes([0.45, 0.3, 0.52, 0.45])\n        axins.step(t_f, St_f, where='post', color='black', linewidth=1.0)\n        axins.fill_between(t_f, lower, upper, step='post', alpha=0.3, color=color)\n        axins.axhline(y=0, color='firebrick', linestyle='--', linewidth=1.2)\n        axins.set_xlim(240, 275)\n        axins.set_ylim(-0.015, 0.015)\n        axins.set_title('tail (zoom): t ∈ [240, 275]', fontsize=8)\n        axins.tick_params(labelsize=7)\n        axins.grid(True, alpha=0.3)\n\nplt.suptitle('Naive vs Log-Log Confidence Intervals — Machine Fleet', fontsize=13)\nplt.tight_layout()\nplt.show()\nplt.close('all')\n\nviolations = np.sum(naive_lower < 0) + np.sum(naive_upper > 1)\nprint(f\"Naive CI boundary violations : {violations} out of {len(t_f)} failure times\")\nprint(f\"Log-log CI boundary violations: {np.sum(ll_lower < 0) + np.sum(ll_upper > 1)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nViolation times    : [252.18 265.55]\nnaive_lower values : [-0.00123213 -0.00224921]\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/fig-km-ci-comparison-output-2.png){#fig-km-ci-comparison width=1332 height=476}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nNaive CI boundary violations : 5 out of 859 failure times\nLog-log CI boundary violations: 0\n```\n:::\n:::\n\n\nThe zoomed inset tells the story. At $t=252$ and $t=265$, the naive CI drops below zero. The dip is tiny but mathematically meaningless. The log-log interval has zero violations, no matter how sparse the risk set gets. For most of the curve the two intervals are indistinguishable. The \ndifference only shows up where $\\hat{S}(t)$ is close to zero and the \nrisk set is small — exactly where the normal approximation breaks down \nand where getting the interval right actually matters.\n\n\n## Tied Failure Times in the Kaplan-Meier Estimator\n\nSo far we have assumed that no two units fail at exactly the same time — \nthe distinct failure times $t_{(1)} < t_{(2)} < \\cdots < t_{(K)}$ are \nstrictly ordered. In real data, this assumption is routinely violated. \nMachines are monitored at discrete time intervals, timestamps are rounded \nto the nearest hour, and sometimes two units genuinely fail simultaneously. \nWhen two or more units share the same recorded failure time, we have a \n**tie**.\n\n### Setup\n\nAt each failure time $t_{(j)}$, define:\n\n- $n_j$ = number of units at risk just before $t_{(j)}$\n- $d_j$ = number of failures at $t_{(j)}$ (now allowed to be $> 1$)\n- $c_j$ = number of censorings at $t_{(j)}$\n\nThe $c_j$ censored units have $Y_i = t_{(j)}$ and $\\delta_i = 0$. All we \nknow about them is: they were alive at $t_{(j)}$ and then left the study. \nWe do not know whether they would have failed at $t_{(j)}$ or survived \npast it.\n\n### The Risk Set Update Rule\n\nAfter processing $t_{(j)}$, the $d_j$ failures and $c_j$ censorings all \nleave the risk set. The risk set size at the next failure time is:\n\n$$n_{j+1} = n_j - d_j - c_j$$\n\nThis is just conservation — units enter the interval, some leave due to \nfailure or censoring, the rest carry forward. This update rule holds \nregardless of how we handle the tie at $t_{(j)}$.\n\n### The Tie-Handling Problem\n\nWe want to estimate the conditional probability of surviving past \n$t_{(j)}$:\n\n$$1 - \\frac{d_j}{n_j}$$\n\nTo compute this we need $n_j$ — the number of machines at risk *when the \nfailures occurred*. The $d_j$ failures are unambiguous. The $c_j$ censored \nunits are the problem: their recorded time is also $t_{(j)}$. Were they \nat risk when the failures happened, or not? We don't know — and this is \nexactly the question the two conventions answer differently.\n\n### Convention A: Censorings Before Failures\n\nConvention A assumes the $c_j$ censored units left the study *before* the \nfailures occurred at $t_{(j)}$. They are removed from the risk set first:\n\n$$n_j^{(A)} = n_j - c_j$$\n\n$$1 - \\frac{d_j}{n_j^{(A)}} = 1 - \\frac{d_j}{n_j - c_j}$$\n\nWith $n_j = 20$, $d_j = 3$, $c_j = 2$:\n\n$$1 - \\frac{3}{20 - 2} = 1 - \\frac{3}{18} = 0.833$$\n\n### Convention B: Failures Before Censorings (Standard KM)\n\nConvention B assumes the $c_j$ censored units were still present when the \nfailures occurred. All $n_j$ units are at risk:\n\n$$n_j^{(B)} = n_j$$\n\n$$1 - \\frac{d_j}{n_j^{(B)}} = 1 - \\frac{d_j}{n_j}$$\n\nWith the same numbers:\n\n$$1 - \\frac{3}{20} = 0.850$$\n\n### Comparing the Two Conventions\n\n| | $n_j$ used | $1 - d_j/n_j$ | $n_{j+1}$ |\n|---|---|---|---|\n| Convention A | $n_j - c_j = 18$ | $0.833$ | $15$ |\n| Convention B | $n_j = 20$ | $0.850$ | $15$ |\n\nNotice that $n_{j+1} = 15$ under both conventions — the tied units all \nleave by $t_{(j+1)}$ regardless. The convention only affects the estimated \nsurvival factor at $t_{(j)}$ itself, not what comes after.\n\nConvention A implicitly assumes the censored units would have survived \npast $t_{(j)}$ — because removing them from the denominator makes the \nfailure rate look higher than it might actually be. Convention B makes no \nsuch assumption: the censored units were present, they were at risk, and \nthen they left. It lets them contribute to $n_j$ — which is the honest \nthing to do given that we genuinely do not know their fate. This is why \nConvention B is the standard KM convention.\n\nFormally, under Convention B:\n\n$$n_j = |\\{i : Y_i \\geq t_{(j)}\\}|$$\n\nwhich includes units that fail at $t_{(j)}$, units censored at $t_{(j)}$, \nand units that survive past $t_{(j)}$. The KM estimator under Convention B \nis therefore:\n\n$$\\hat{S}(t) = \\prod_{t_{(j)} \\leq t} \\left(1 - \\frac{d_j}{n_j}\\right)$$\n\nexactly as before — the formula is unchanged. Ties required no new \nmachinery, only a careful convention about the order of events within a \ntied time point.\n\n### Does Our Fleet Have Ties?\n\n::: {#ties-check .cell execution_count=4}\n``` {.python .cell-code}\nimport pandas as pd\n\ndf = pd.read_csv('../../data/machine_fleet.csv')\n\nfailures   = df[df['event_observed'] == 1]['observed_time']\ntie_counts = failures.value_counts()\nties       = tie_counts[tie_counts > 1]\n\nprint(f\"Total failure times      : {len(failures)}\")\nprint(f\"Distinct failure times   : {failures.nunique()}\")\nprint(f\"Tied failure times       : {len(ties)}\")\n\nif len(ties) > 0:\n    print(f\"\\nTop 5 ties:\")\n    print(ties.head())\nelse:\n    print(\"No ties in this dataset.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTotal failure times      : 886\nDistinct failure times   : 859\nTied failure times       : 27\n\nTop 5 ties:\nobserved_time\n72.48     2\n55.03     2\n194.47    2\n52.83     2\n46.77     2\nName: count, dtype: int64\n```\n:::\n:::\n\n\nEven though the synthetic fleet was generated with continuous failure times, the output tells a different story. Out of 886 failures, there are 27 tied failure times. In real telemetry- where failure times are recorded at fixed intervals- ties are almost guaranteed and would be far more frequent. Convention B is what `lifelines` applies by default, so our earlier KM estimates already handle the ties correctly without any additional code. As a bonus: `lifelines` also defaults to the log-log confidence \ninterval. The 5 boundary violations in Figure 3 came from our own \nmanually computed naive CI — we built it from scratch deliberately to \nshow the problem. The shaded band in Figure 1, produced by \n`kmf.plot_survival_function(ci_show=True)`, was already using \nthe log-log transformation all along.\n\n\n## The Log-Rank Test\n\nWe have a powerful tool- the KM estimator for estimating the survival function of a population from data. \nIn practice, we want to compare survival curves across groups. Do machines from manufacturer A last longer than manufacturer B? Does operating environment- indoor vs harsh- affect survival. These are the questions that drive maintenance scheduling and warranty decisions. \n\nThe natural first step is to plot the KM curves for each group side by \nside and look. But looking is not enough. The curves will almost always \ndiffer — if only due to random sampling variability. The question is \nwhether the observed difference is large enough to be real, or whether \nit could possibly have arisen by chance even if the two groups had \nidentical survival functions.\n\nThis is a hypothesis testing problem. We want to test:\n\n$$H_0: S_1(t) = S_2(t) = \\cdots = S_k(t) \\quad \\text{for all } t$$\n\nagainst the alternative that at least one group has a different survival \nfunction. The **log-rank test** is the standard non-parametric test for \nthis. It requires no distributional assumptions — no Weibull, no \nexponential — just the KM structure we have already built.\n\n### The Core Idea: Observed vs Expected Failures\n\nHere is the key insight. At every failure time $t_{(j)}$ in the \ndata, machines from all $k$ groups sit together in the risk set, where $k$ is the number of environmental conditions or manufacturers or something else. Some \nfail, some don't. Under $H_0$ — all groups have the same survival \nfunction — group membership is irrelevant. A machine from manufacturer A \nis no more or less likely to fail at $t_{(j)}$ than a machine from \nmanufacturer C. The failures should be distributed across groups in \nproportion to their share of the risk set.\n\nThe log-rank test asks: across all failure times, do the observed \nfailures in each group match what we would expect under $H_0$?\n\n### The Hypergeometric Distribution\n\nTo make this precise, we need a probability model for the failures at \neach $t_{(j)}$. Here is the random experiment. Consider two groups A and B. \n\nAt failure time $t_{(j)}$, you have $n_j$ machines in the risk set. \nThink of this as a bag of $n_j$ marbles:\n\n- $n_{Aj}$ blue marbles — machines from group A\n- $n_{Bj} = n_j - n_{Aj}$ red marbles — machines from group B\n\nExactly $d_j$ machines fail at $t_{(j)}$. Think of this as drawing $d_j$ \nmarbles from the bag **without replacement** — once a machine fails, it \ndoes not return to the risk set.\n\nThe random variable of interest is:\n\n$$X = d_{Aj} = \\text{number of failures from group A at time } t_{(j)}$$\n\nUnder $H_0$, every machine is equally likely to fail regardless of group \nmembership — no marble is special. So $X$ tells us: out of $d_j$ \nrandomly drawn machines, how many happen to be from group A?\n\n#### PMF of the Hypergeometric\n\nWe want $P(X = x)$ — the probability that exactly $x$ of the $d_j$ \nfailures come from group A.\n\nWe use the classical definition of probability:\n\n$$P(X = x) = \\frac{\\text{number of favourable outcomes}}{\\text{total number of outcomes}}$$\n\nThis applies here because under $H_0$, every possible selection of $d_j$ \nmachines from the $n_j$ at risk is equally likely — no machine is special.\n\n**Total outcomes:** The number of ways to choose $d_j$ machines to fail \nfrom $n_j$ machines at risk:\n\n$$\\binom{n_j}{d_j}$$\n\n**Favourable outcomes:** We want exactly $x$ failures from group A and \n$d_j - x$ failures from group B. These are independent choices:\n\n- Choose $x$ machines from group A's $n_{Aj}$: $\\binom{n_{Aj}}{x}$ ways\n- Choose $d_j - x$ machines from group B's $n_{Bj}$: $\\binom{n_{Bj}}{d_j - x}$ ways\n\nBy the multiplication principle, the number of favourable outcomes is:\n\n$$\\binom{n_{Aj}}{x} \\binom{n_{Bj}}{d_j - x}$$\n\nTherefore:\n\n$$P(X = x) = \\frac{\\dbinom{n_{Aj}}{x}\\dbinom{n_{Bj}}{d_j - x}}{\\dbinom{n_j}{d_j}}$$\n\nThe range of $x$ is $\\max(0,\\ d_j - n_{Bj}) \\leq x \\leq \\min(d_j,\\ n_{Aj})$.\n\n**Upper bound:** $x$ cannot exceed the number of group A machines at risk \n$n_{Aj}$, nor the total failures $d_j$. So $x \\leq \\min(d_j,\\ n_{Aj})$.\n\n**Lower bound:** The number of failures from group B is $d_j - x$, which \ncannot exceed $n_{Bj}$. So $x \\geq \\max(0,\\ d_j - n_{Bj})$.\n\nWe say $X \\sim \\text{Hypergeometric}(n_j, n_{Aj}, d_j)$.\n\n#### Mean and Variance\n\nThe mean and variance of $X \\sim \\text{Hypergeometric}(n_j, n_{Aj}, d_j)$ \nare:\n\n$$e_{Aj} = \\mathbb{E}[X] = d_j \\cdot \\frac{n_{Aj}}{n_j}$$\n\n$$\\text{Var}(X) = d_j \\cdot \\frac{n_{Aj}}{n_j} \\cdot \n\\frac{n_{Bj}}{n_j} \\cdot \\frac{n_j - d_j}{n_j - 1}$$\n\nThe mean has a clean interpretation: if group A owns $n_{Aj}/n_j$ \nfraction of the risk set, it should own the same fraction of the $d_j$ \nfailures under $H_0$. The extra factor $\\frac{n_j - d_j}{n_j - 1}$ in \nthe variance is the **finite population correction** — the price of \nsampling without replacement from a finite bag. As $n_j \\to \\infty$, \nthis factor approaches 1 and the variance converges to that of a \nbinomial.\n\n### The Hypothesis Test \nNow recall what we are trying to do. We have two groups — manufacturer A \nand manufacturer B — and we want to know if their survival functions are \nthe same. We are testing:\n\n$$H_0: S_A(t) = S_B(t) \\quad \\text{for all } t$$\n\nAt each failure time $t_{(j)}$, we now have:\n\n- $d_{Aj}$ — the **observed** number of failures from group A\n- $e_{Aj} = d_j \\cdot \\frac{n_{Aj}}{n_j}$ — the **expected** number of \nfailures from group A under $H_0$\n\nLet's make this concrete. Suppose at failure time $t_{(j)} = 1000$ hours:\n\n| | Machines at risk | Failures observed | Failure rate |\n|---|---|---|---|\n| Group A | 300 | 20 | $20/300 = 6.7\\%$ |\n| Group B | 400 | 10 | $10/400 = 2.5\\%$ |\n| **Total** | **700** | **30** | $30/700 = 4.3\\%$ |\n\nGroup A's failure rate is nearly three times group B's. But is this a \nreal difference or just random chance?\n\nUnder $H_0$, both groups have the same survival function — so failures \nshould occur in proportion to each group's share of the risk set. Group \nA owns $300/700$ of the risk set, group B owns $400/700$. Applying this \nto the 30 total failures:\n\n$$e_{Aj} = 30 \\times \\frac{300}{700} = 12.86 \\qquad \ne_{Bj} = 30 \\times \\frac{400}{700} = 17.14$$\n\nThe discrepancies at this single failure time are:\n\n$$d_{Aj} - e_{Aj} = 20 - 12.86 = +7.14 \\qquad \\text{(group A fails more than expected)}$$\n$$d_{Bj} - e_{Bj} = 10 - 17.14 = -7.14 \\qquad \\text{(group B fails less than expected)}$$\n\nNotice they are equal and opposite — if group A has 7.14 excess failures, \ngroup B must have 7.14 fewer, since the total is fixed at 30. This is \nalways true: $U_A = -U_B$, which is why we only need to track one group.\n\nThis is just one failure time. The log-rank test aggregates this \ndiscrepancy across all $K$ failure times:\n\n$$U_A = \\sum_{j=1}^{K} (d_{Aj} - e_{Aj}) = O_A - E_A$$\n\nwhere $O_A = \\sum_j d_{Aj}$ is the total observed failures from group A \nand $E_A = \\sum_j e_{Aj}$ is the total expected failures under $H_0$. \nIf $H_0$ is true, $U_A \\approx 0$. Large $|U_A|$ is evidence against \n$H_0$. The question is: how large is large enough?\n\n#### The Log-Rank Test Statistic\n\nTo answer \"how large is large enough\", we need to account for the \nvariability of $U_A$. Since the $d_{Aj}$ are independent across failure \ntimes — the risk sets at different failure times are disjoint, exactly \nas we argued for Greenwood's formula — the variance of $U_A$ is the sum \nof the variances at each failure time:\n\n$$\\text{Var}(U_A) = \\sum_{j=1}^{K} \\text{Var}(d_{Aj}) = \n\\sum_{j=1}^{K} d_j \\cdot \\frac{n_{Aj}}{n_j} \\cdot \n\\frac{n_{Bj}}{n_j} \\cdot \\frac{n_j - d_j}{n_j - 1}$$\n\nCall this $V_A$. By the central limit theorem, for large samples \n$U_A / \\sqrt{V_A}$ is approximately standard normal. Squaring gives the \nlog-rank test statistic:\n\n$$\\boxed{\\chi^2 = \\frac{U_A^2}{V_A} = \\frac{(O_A - E_A)^2}{V_A}}$$\n\nwhich follows a $\\chi^2$ distribution with **1 degree of freedom** under \n$H_0$. We reject $H_0$ at significance level $\\alpha$ if:\n\n$$\\chi^2 > \\chi^2_{1,\\ 1-\\alpha}$$\n\nFor $\\alpha = 0.05$, the critical value is $\\chi^2_{1,\\ 0.95} = 3.84$.\nIn practice, we compute the $p$-value:\n\n$$p = P(\\chi^2_1 > \\chi^2_{\\text{observed}})$$\n\nIf $p < 0.05$, we reject $H_0$ and conclude that the two groups have \nstatistically different survival functions. If $p \\geq 0.05$, we fail to \nreject $H_0$ — the observed difference in KM curves is consistent with \nrandom sampling variability.\n\n\n### Extension to $k$ Groups\n\nFor $k$ groups, the same logic applies. At each failure time $t_{(j)}$, \ndefine $e_{gj} = d_j \\cdot n_{gj}/n_j$ for each group $g$. The \ndiscrepancy for group $g$ is:\n\n$$U_g = \\sum_{j=1}^{K} (d_{gj} - e_{gj}) = O_g - E_g$$\n\nNote that $\\sum_{g=1}^{k} U_g = 0$ — the discrepancies sum to zero \nacross all groups, since observed and expected totals both equal $\\sum_j \nd_j$. So only $k-1$ of the $U_g$ are independent.\n\nThe test statistic generalises to a quadratic form. Let \n$\\mathbf{U} = (U_1, U_2, \\ldots, U_{k-1})^T$ be the vector of \ndiscrepancies for the first $k-1$ groups, and let $\\mathbf{V}$ be the \n$(k-1) \\times (k-1)$ covariance matrix with entries:\n\n$$V_{gg} = \\sum_{j=1}^{K} \\text{Var}(d_{gj}), \\qquad \nV_{gh} = -\\sum_{j=1}^{K} \\frac{d_j \\cdot n_{gj} \\cdot n_{hj}}{n_j^2} \n\\cdot \\frac{n_j - d_j}{n_j - 1} \\quad (g \\neq h)$$\n\nThe log-rank statistic is:\n\n$$\\chi^2 = \\mathbf{U}^T \\mathbf{V}^{-1} \\mathbf{U}$$\n\nwhich follows a $\\chi^2$ distribution with $k-1$ degrees of freedom \nunder $H_0$. For $\\alpha = 0.05$, we reject $H_0$ if:\n\n$$p = P(\\chi^2_{k-1} > \\chi^2_{\\text{observed}}) < 0.05$$\n\nNote that for $k = 2$ this reduces exactly to the two-sample formula \nabove.\n\nDoes manufacturer or operating environment affect survival in our fleet? \nThe KM curves will tell the story visually — but the log-rank test will \ntell us whether the differences are statistically significant. We run \ntwo tests: one comparing the three manufacturers, and one comparing the \nthree operating environments.\n\n::: {#cell-fig-logrank .cell execution_count=5}\n``` {.python .cell-code}\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom lifelines import KaplanMeierFitter\nfrom lifelines.statistics import multivariate_logrank_test, pairwise_logrank_test\n\nplt.close('all')\n\ndf = pd.read_csv('../../data/machine_fleet.csv')\n\nfig, axes = plt.subplots(1, 2, figsize=(14, 5))\n\n# ── Manufacturer ──────────────────────────────────────────────────────────────\nax = axes[0]\nfor mfr, color in zip(['A', 'B', 'C'], ['steelblue', 'firebrick', 'seagreen']):\n    mask = df['manufacturer'] == mfr\n    kmf  = KaplanMeierFitter()\n    kmf.fit(df.loc[mask, 'observed_time'],\n            event_observed=df.loc[mask, 'event_observed'],\n            label=f'Manufacturer {mfr}')\n    kmf.plot_survival_function(ax=ax, ci_show=False, color=color)\n\nax.set_xlabel('Time (hours)', fontsize=12)\nax.set_ylabel(r'$\\hat{S}(t)$', fontsize=12)\nax.set_title('KM Curves by Manufacturer', fontsize=13)\nax.grid(True, alpha=0.3)\n\n# ── Environment ───────────────────────────────────────────────────────────────\nax = axes[1]\nfor env, color in zip(['indoor', 'outdoor', 'harsh'], ['steelblue', 'firebrick', 'seagreen']):\n    mask = df['environment'] == env\n    kmf  = KaplanMeierFitter()\n    kmf.fit(df.loc[mask, 'observed_time'],\n            event_observed=df.loc[mask, 'event_observed'],\n            label=env.capitalize())\n    kmf.plot_survival_function(ax=ax, ci_show=False, color=color)\n\nax.set_xlabel('Time (hours)', fontsize=12)\nax.set_ylabel(r'$\\hat{S}(t)$', fontsize=12)\nax.set_title('KM Curves by Environment', fontsize=13)\nax.grid(True, alpha=0.3)\n\nplt.suptitle('Kaplan-Meier Curves by Group — Machine Fleet', fontsize=13)\nplt.tight_layout()\nplt.show()\nplt.close('all')\n\n# ── Log-rank tests ────────────────────────────────────────────────────────────\nprint(\"=\" * 55)\nprint(\"LOG-RANK TEST: Manufacturer (k=3, df=2)\")\nprint(\"=\" * 55)\nres_mfr = multivariate_logrank_test(\n    df['observed_time'],\n    df['manufacturer'],\n    event_observed=df['event_observed']\n)\nprint(f\"Test statistic : {res_mfr.test_statistic:.4f}\")\nprint(f\"p-value        : {res_mfr.p_value:.6f}\")\nprint(f\"Degrees of freedom: 2\")\nprint(f\"Conclusion     : {'Reject H0' if res_mfr.p_value < 0.05 else 'Fail to reject H0'} at alpha=0.05\")\n\nprint()\nprint(\"=\" * 55)\nprint(\"LOG-RANK TEST: Environment (k=3, df=2)\")\nprint(\"=\" * 55)\nres_env = multivariate_logrank_test(\n    df['observed_time'],\n    df['environment'],\n    event_observed=df['event_observed']\n)\nprint(f\"Test statistic : {res_env.test_statistic:.4f}\")\nprint(f\"p-value        : {res_env.p_value:.6f}\")\nprint(f\"Degrees of freedom: 2\")\nprint(f\"Conclusion     : {'Reject H0' if res_env.p_value < 0.05 else 'Fail to reject H0'} at alpha=0.05\")\n\n# ── Pairwise follow-up ────────────────────────────────────────────────────────\nprint()\nprint(\"=\" * 55)\nprint(\"PAIRWISE LOG-RANK: Manufacturer\")\nprint(\"=\" * 55)\npw_mfr = pairwise_logrank_test(\n    df['observed_time'],\n    df['manufacturer'],\n    event_observed=df['event_observed']\n)\nprint(pw_mfr.summary[['p']])\n\nprint()\nprint(\"=\" * 55)\nprint(\"PAIRWISE LOG-RANK: Environment\")\nprint(\"=\" * 55)\npw_env = pairwise_logrank_test(\n    df['observed_time'],\n    df['environment'],\n    event_observed=df['event_observed']\n)\nprint(pw_env.summary[['p']])\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/fig-logrank-output-1.png){#fig-logrank width=1332 height=476}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n=======================================================\nLOG-RANK TEST: Manufacturer (k=3, df=2)\n=======================================================\nTest statistic : 59.9543\np-value        : 0.000000\nDegrees of freedom: 2\nConclusion     : Reject H0 at alpha=0.05\n\n=======================================================\nLOG-RANK TEST: Environment (k=3, df=2)\n=======================================================\nTest statistic : 55.3310\np-value        : 0.000000\nDegrees of freedom: 2\nConclusion     : Reject H0 at alpha=0.05\n\n=======================================================\nPAIRWISE LOG-RANK: Manufacturer\n=======================================================\n                p\nA B  3.272446e-01\n  C  1.441062e-12\nB C  8.861906e-11\n\n=======================================================\nPAIRWISE LOG-RANK: Environment\n=======================================================\n                           p\nharsh  indoor   4.004801e-13\n       outdoor  5.839594e-04\nindoor outdoor  3.940472e-06\n```\n:::\n:::\n\n\nThe plots tell a clear story.\n\n**Manufacturer (left panel):** Manufacturers A and B are nearly \nindistinguishable — their curves run almost on top of each other for the \nentire duration. Manufacturer C is the outlier: its curve drops sharply \nin the first 50 hours and reaches zero well before A and B. If you were \na fleet manager, you would already be on the phone with manufacturer C's \nsales representative.\n\n**Environment (right panel):** There is a clean ordering across all \nthree environments. Indoor machines survive the longest, outdoor machines \nfall in the middle, and harsh environment machines degrade the fastest. \nUnlike the manufacturer plot, all three curves are visually separated \nfrom the very beginning — the effect of operating environment kicks in \nimmediately, not just in the tail.\n\nThe log-rank test confirms what the eye already sees. Here is the summary\n\n**Log-Rank Test Results:**\n\n| Group | Test statistic | Degrees of freedom | $p$-value | Conclusion |\n|---|---|---|---|---|\n| Manufacturer | 59.95 | 2 | $< 0.001$ | Reject $H_0$ |\n| Environment | 55.33 | 2 | $< 0.001$ | Reject $H_0$ |\n\n**Pairwise tests — Manufacturer:**\n\n| Comparison | $p$-value | Significant? |\n|---|---|---|\n| A vs B | $0.327$ | No |\n| A vs C | $1.4 \\times 10^{-12}$ | Yes |\n| B vs C | $8.9 \\times 10^{-11}$ | Yes |\n\n**Pairwise tests — Environment:**\n\n| Comparison | $p$-value | Significant? |\n|---|---|---|\n| Harsh vs Indoor | $4.0 \\times 10^{-13}$ | Yes |\n| Harsh vs Outdoor | $5.8 \\times 10^{-4}$ | Yes |\n| Indoor vs Outdoor | $3.9 \\times 10^{-6}$ | Yes |\n\n\n## Conclusion\n\nThat was a long journey — but a rewarding one. Let's take stock of what \nwe built in Part 4.\n\nWe started with a simple question: can we estimate the survival function from censored data without assuming any parametric form? The answer is yes- and the tool is\nthe OG of survival analysis estimators- the **Kaplan-Meier estimator** derived from nothing more than conditional probability and a counting argument. \n\nAfter fitting the KM estimator, we then asked: how uncertain is this estimate which led us to **Greenwood's Formula** to estimate the survival function's variance. \n\n$$\\widehat{\\text{Var}}(\\hat{S}(t)) = [\\hat{S}(t)]^2 \\sum_{t_{(j)} \\leq t} \n\\frac{d_j}{n_j(n_j - d_j)}$$\n\nWe turned that variance into a **confidence interval** — and saw why the \nnaive linear interval fails near the tails, and how the **log-log \ntransformation** fixes it.\n\nWe handled **tied failure times** - real data always has them - and saw that the KM formula requires no modification but just a convention about the ordering of events. \n\nFinally, we asked: do different groups have different survival functions? \nThe **log-rank test** gave us a rigorous answer. In our fleet, both \nmanufacturer and operating environment have statistically significant \neffects on survival — $p < 0.001$ in both cases. Manufacturer C fails \nfaster than A and B. Harsh environments degrade machines faster than \nindoor or outdoor conditions.\n\nThe log-rank test told us that manufacturer and environment both \nsignificantly affect survival in our fleet. But it only answers a \npopulation-level question: do these groups differ? In practice, we want \nto ask a more personalised question — not \"do harsh environment machines \nfail faster on average?\" but \"what is the survival probability for \n*this* machine, given that it is 8 years old, running at high load, \noperating at 110°C, with a vibration level of 6.2?\"\n\nThat is a question about a specific machine with a specific covariate \nvector $\\mathbf{X} = (X_1, X_2, \\ldots, X_p)^T$ — age, load factor, \noperating temperature, vibration level, and so on. To answer it, we need \na model that takes $\\mathbf{X}$ as input and outputs a survival function. \nThat model is the **Cox Proportional Hazards model**, and it is the \nsubject of Part 5.\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}